
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Nov 19 2018 14:06:57 CET (Nov 19 2018 13:06:57 UTC)

// Verification Directory fv/permut_sel_aio 

module permut_sel_aio(clk, resn, en, sel, ready, init, amp_enable,
     cout);
  input clk, resn, en;
  input [15:0] sel;
  output ready, init, amp_enable;
  output [7:0] cout;
  wire clk, resn, en;
  wire [15:0] sel;
  wire ready, init, amp_enable;
  wire [7:0] cout;
  wire [15:0] swp_cnt;
  wire [2:0] \array[3] ;
  wire [2:0] \array[4] ;
  wire [2:0] \array[5] ;
  wire [2:0] \array[6] ;
  wire [2:0] \array[2] ;
  wire [2:0] \array[1] ;
  wire [2:0] \array[0] ;
  wire [2:0] \array[7] ;
  wire [2:0] \c[7] ;
  wire [2:0] \c[4] ;
  wire [2:0] \c[5] ;
  wire [2:0] \c[6] ;
  wire [3:0] i;
  wire [2:0] \c[2] ;
  wire [2:0] \c[3] ;
  wire [2:0] \c[1] ;
  wire [7:0] stepcount;
  wire [7:0] waitcount;
  wire [7:0] cout_r;
  wire [7:0] state;
  wire [7:0] next_state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, n_0, n_1,
       n_4, n_6;
  wire n_7, n_8, n_10, n_12, n_14, n_15, n_18, n_28;
  wire n_29, n_31, n_33, n_35, n_36, n_38, n_40, n_41;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_94, n_95, n_96, n_98, n_99, n_100, n_101, n_102;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_153;
  wire n_154, n_155, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_164, n_165, n_166, n_168, n_169, n_170, n_171, n_172;
  wire n_173, n_174, n_175, n_176, n_177, n_178, n_180, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_223, n_224;
  wire n_225, n_226, n_232, n_233, n_234, n_235, n_238, n_240;
  wire n_241, n_242, n_243, n_244, n_245, n_246, n_247, n_248;
  wire n_249, n_250, n_251, n_252, n_253, n_254, n_255, n_256;
  wire n_258, n_259, n_260, n_268, n_270, n_272, n_273, n_275;
  wire n_276, n_278, n_279, n_280, n_281, n_282, n_283, n_284;
  wire n_285, n_287, n_288, n_289, n_290, n_291, n_292, n_293;
  wire n_294, n_295, n_296, n_297, n_298, n_299, n_300, n_301;
  wire n_302, n_303, n_304, n_305, n_306, n_307, n_308, n_310;
  wire n_311, n_312, n_313, n_314, n_315, n_317, n_318, n_319;
  wire n_320, n_321, n_322, n_323, n_324, n_325, n_326, n_327;
  wire n_328, n_329, n_330, n_331, n_332, n_333, n_334, n_335;
  wire n_336, n_337, n_338, n_339, n_340, n_341, n_342, n_343;
  wire n_344, n_345, n_346, n_347, n_348, n_350, n_351, n_352;
  wire n_353, n_354, n_355, n_356, n_357, n_358, n_359, n_360;
  wire n_361, n_362, n_363, n_364, n_365, n_366, n_367, n_368;
  wire n_369, n_370, n_371, n_372, n_373, n_374, n_375, n_376;
  wire n_377, n_378, n_379, n_380, n_381, n_382, n_383, n_384;
  wire n_385, n_386, n_387, n_388, n_389, n_390, n_391, n_392;
  wire n_393, n_394, n_395, n_396, n_397, n_398, n_399, n_400;
  wire n_401, n_402, n_403, n_404, n_405, n_406, n_407, n_408;
  wire n_409, n_410, n_411, n_412, n_413, n_414, n_415, n_416;
  wire n_417, n_418, n_419, n_420, n_421, n_422, n_423, n_424;
  wire n_425, n_426, n_427, n_428, n_429, n_430, n_431, n_432;
  wire n_433, n_434, n_435, n_436, n_437, n_438, n_440, n_441;
  wire n_442, n_443, n_444, n_445, n_446, n_447, n_448, n_449;
  wire n_450, n_451, n_452, n_453, n_454, n_455, n_456, n_457;
  wire n_458, n_459, n_460, n_461, n_462, n_463, n_464, n_465;
  wire n_466, n_467, n_468, n_469, n_470, n_471, n_472, n_473;
  wire n_474, n_475, n_476, n_477, n_478, n_479, n_480, n_481;
  wire n_482, n_483, n_484, n_485, n_486, n_487, n_488, n_489;
  wire n_490, n_491, n_492, n_494, n_495, n_496, n_498, n_499;
  wire n_500, n_520, n_521, n_522, n_523, n_524, n_525, n_526;
  wire n_527, n_530, n_531, n_538, n_539, n_540, n_541, n_542;
  wire n_543, n_544, n_545, n_546, n_547, n_548, n_549, n_550;
  wire n_551, ready_1083;
  DFSH \swp_cnt_reg[15] (.C (clk), .D (n_500), .Q (swp_cnt[15]));
  DFSH \array_reg[3][1] (.C (clk), .D (n_498), .Q (\array[3] [1]));
  DFSH \array_reg[3][0] (.C (clk), .D (n_499), .Q (\array[3] [0]));
  DFSH \array_reg[4][2] (.C (clk), .D (n_496), .Q (\array[4] [2]));
  NOR2XL g14185__8780(.A (n_521), .B (n_479), .O (n_500));
  DFSH \array_reg[5][2] (.C (clk), .D (n_490), .Q (\array[5] [2]));
  DFSH \array_reg[6][2] (.C (clk), .D (n_482), .Q (\array[6] [2]));
  DFSH \array_reg[6][1] (.C (clk), .D (n_481), .Q (\array[6] [1]));
  DFSH \array_reg[2][1] (.C (clk), .D (n_489), .Q (\array[2] [1]));
  NAND2 g14208__4296(.A (n_486), .B (n_427), .O (n_499));
  NAND2 g14209__3772(.A (n_487), .B (n_427), .O (n_498));
  DFSH \array_reg[5][0] (.C (clk), .D (n_492), .Q (\array[5] [0]));
  DFSH \array_reg[4][0] (.C (clk), .D (n_491), .Q (\array[4] [0]));
  DFSH \array_reg[4][1] (.C (clk), .D (n_495), .Q (\array[4] [1]));
  OR211AXL g14210__1474(.A (n_471), .B (n_494), .C (n_456), .D (n_427),
       .O (n_496));
  DFSH \array_reg[5][1] (.C (clk), .D (n_477), .Q (\array[5] [1]));
  DFSH \swp_cnt_reg[14] (.C (clk), .D (n_480), .Q (swp_cnt[14]));
  DFSH \array_reg[2][2] (.C (clk), .D (n_472), .Q (\array[2] [2]));
  DFSH \array_reg[2][0] (.C (clk), .D (n_475), .Q (\array[2] [0]));
  DFSH \array_reg[6][0] (.C (clk), .D (n_478), .Q (\array[6] [0]));
  DFSH \array_reg[1][0] (.C (clk), .D (n_476), .Q (\array[1] [0]));
  OR21AXL g14232__4547(.A (n_494), .B (n_488), .C (n_448), .O (n_495));
  NAND2 g14211__2683(.A (n_450), .B (n_427), .O (n_492));
  OR21AXL g14231__1309(.A (n_494), .B (n_473), .C (n_453), .O (n_491));
  DFSH \array_reg[1][1] (.C (clk), .D (n_454), .Q (\array[1] [1]));
  DFSH \array_reg[3][2] (.C (clk), .D (n_467), .Q (\array[3] [2]));
  DFSH \array_reg[0][0] (.C (clk), .D (n_455), .Q (\array[0] [0]));
  NAND2 g14204__6877(.A (n_466), .B (n_427), .O (n_490));
  OR211AXL g14207__2900(.A (n_488), .B (n_474), .C (n_441), .D (n_427),
       .O (n_489));
  AND222OXL g14214__2391(.A (n_485), .B (n_469), .C (n_484), .D
       (\array[3] [1]), .E (n_468), .F (n_483), .O (n_487));
  AND222OXL g14215__7675(.A (n_485), .B (n_461), .C (n_484), .D
       (\array[3] [0]), .E (n_449), .F (n_483), .O (n_486));
  NAND2 g14206__7118(.A (n_447), .B (n_427), .O (n_482));
  NAND2 g14205__8757(.A (n_460), .B (n_427), .O (n_481));
  DFSH \array_reg[0][1] (.C (clk), .D (n_445), .Q (\array[0] [1]));
  DFSH \array_reg[0][2] (.C (clk), .D (n_442), .Q (\array[0] [2]));
  NOR2XL g14212__1786(.A (n_438), .B (n_479), .O (n_480));
  DFSH \array_reg[7][1] (.C (clk), .D (n_428), .Q (\array[7] [1]));
  DFSH \array_reg[7][2] (.C (clk), .D (n_434), .Q (\array[7] [2]));
  DFSH \array_reg[7][0] (.C (clk), .D (n_423), .Q (\array[7] [0]));
  DFSH \array_reg[1][2] (.C (clk), .D (n_436), .Q (\array[1] [2]));
  INV g14226(.A (n_462), .O (n_478));
  INV g14225(.A (n_470), .O (n_477));
  NAND2 g14216__5953(.A (n_433), .B (n_427), .O (n_476));
  OR21AXL g14229__5703(.A (n_474), .B (n_473), .C (n_426), .O (n_475));
  OR21AXL g14230__7114(.A (n_474), .B (n_471), .C (n_422), .O (n_472));
  DFSH \swp_cnt_reg[7] (.C (clk), .D (n_440), .Q (swp_cnt[7]));
  AND222OXL g14234__5266(.A (n_465), .B (n_469), .C (n_464), .D
       (\array[5] [1]), .E (n_468), .F (n_463), .O (n_470));
  OR222AXL g14213__2250(.A (n_380), .B (n_14), .C (n_435), .D (n_411),
       .E (n_471), .F (n_341), .O (n_467));
  AND222OXL g14235__6083(.A (n_465), .B (n_446), .C (n_464), .D
       (\array[5] [2]), .E (n_407), .F (n_463), .O (n_466));
  AND222OXL g14236__2703(.A (n_459), .B (\array[0] [0]), .C (n_458), .D
       (n_461), .E (n_457), .F (\array[6] [0]), .O (n_462));
  AND222OXL g14233__5795(.A (n_459), .B (\array[0] [1]), .C (n_458), .D
       (n_469), .E (n_457), .F (\array[6] [1]), .O (n_460));
  DFSH \swp_cnt_reg[0] (.C (clk), .D (n_413), .Q (swp_cnt[0]));
  DFSH \swp_cnt_reg[4] (.C (clk), .D (n_418), .Q (swp_cnt[4]));
  DFSH \swp_cnt_reg[6] (.C (clk), .D (n_416), .Q (swp_cnt[6]));
  DFSH \swp_cnt_reg[5] (.C (clk), .D (n_417), .Q (swp_cnt[5]));
  DFSH \swp_cnt_reg[8] (.C (clk), .D (n_419), .Q (swp_cnt[8]));
  DFSH \swp_cnt_reg[11] (.C (clk), .D (n_412), .Q (swp_cnt[11]));
  DFSH \swp_cnt_reg[9] (.C (clk), .D (n_421), .Q (swp_cnt[9]));
  AND22OXL g14265__7344(.A (n_452), .B (\array[4] [2]), .C (n_451), .D
       (\array[0] [2]), .O (n_456));
  OR2N2AXL g14268__1840(.A (\array[0] [0]), .B (n_444), .C (n_443), .D
       (n_473), .O (n_455));
  INV g14253(.A (n_432), .O (n_454));
  AND22OXL g14263__5019(.A (n_452), .B (\array[4] [0]), .C (n_451), .D
       (\array[0] [0]), .O (n_453));
  AND222OXL g14227__1857(.A (n_465), .B (n_461), .C (n_464), .D
       (\array[5] [0]), .E (n_449), .F (n_463), .O (n_450));
  AND22OXL g14264__9906(.A (n_452), .B (\array[4] [1]), .C (n_451), .D
       (\array[0] [1]), .O (n_448));
  AND222OXL g14228__8780(.A (n_459), .B (\array[0] [2]), .C (n_458), .D
       (n_446), .E (n_457), .F (\array[6] [2]), .O (n_447));
  OR2N2AXL g14266__4296(.A (\array[0] [1]), .B (n_444), .C (n_443), .D
       (n_488), .O (n_445));
  OR2N2AXL g14267__3772(.A (\array[0] [2]), .B (n_444), .C (n_443), .D
       (n_471), .O (n_442));
  DFSH \swp_cnt_reg[12] (.C (clk), .D (n_420), .Q (swp_cnt[12]));
  DFSH \swp_cnt_reg[13] (.C (clk), .D (n_414), .Q (swp_cnt[13]));
  DFSH \swp_cnt_reg[10] (.C (clk), .D (n_415), .Q (swp_cnt[10]));
  AND22OXL g14254__1474(.A (n_425), .B (\array[2] [1]), .C (n_424), .D
       (\array[0] [1]), .O (n_441));
  NOR2XL g14297__4547(.A (n_402), .B (n_479), .O (n_440));
  MUX21XL g14237__2683(.A (swp_cnt[14]), .B (n_399), .SA (n_437), .O
       (n_438));
  DFSH \swp_cnt_reg[1] (.C (clk), .D (n_409), .Q (swp_cnt[1]));
  DFSH \swp_cnt_reg[2] (.C (clk), .D (n_410), .Q (swp_cnt[2]));
  DFSH \swp_cnt_reg[3] (.C (clk), .D (n_406), .Q (swp_cnt[3]));
  OR222AXL g14259__1309(.A (n_379), .B (n_6), .C (n_435), .D (n_387),
       .E (n_471), .F (n_340), .O (n_436));
  NAND2 g14256__6877(.A (n_408), .B (n_427), .O (n_434));
  AND222OXL g14257__2900(.A (n_449), .B (n_431), .C (n_430), .D
       (n_461), .E (n_429), .F (\array[1] [0]), .O (n_433));
  AND222OXL g14258__2391(.A (n_468), .B (n_431), .C (n_430), .D
       (n_469), .E (n_429), .F (\array[1] [1]), .O (n_432));
  NAND2 g14255__7675(.A (n_405), .B (n_427), .O (n_428));
  AND22OXL g14260__7118(.A (n_425), .B (\array[2] [0]), .C (n_424), .D
       (\array[0] [0]), .O (n_426));
  NAND2 g14261__8757(.A (n_401), .B (n_427), .O (n_423));
  AND22OXL g14262__1786(.A (n_425), .B (\array[2] [2]), .C (n_424), .D
       (\array[0] [2]), .O (n_422));
  NOR2XL g14299__5953(.A (n_376), .B (n_479), .O (n_421));
  NOR2XL g14302__5703(.A (n_374), .B (n_479), .O (n_420));
  NOR2XL g14289__7114(.A (n_381), .B (n_479), .O (n_419));
  NOR2XL g14294__5266(.A (n_385), .B (n_479), .O (n_418));
  NOR2XL g14295__2250(.A (n_383), .B (n_479), .O (n_417));
  NOR2XL g14296__6083(.A (n_382), .B (n_479), .O (n_416));
  NOR2XL g14300__2703(.A (n_375), .B (n_479), .O (n_415));
  DFSH \c_reg[7][2] (.C (clk), .D (n_370), .Q (\c[7] [2]));
  DFSH \c_reg[7][0] (.C (clk), .D (n_353), .Q (\c[7] [0]));
  DFSH \c_reg[4][0] (.C (clk), .D (n_369), .Q (\c[4] [0]));
  DFSH \c_reg[4][1] (.C (clk), .D (n_368), .Q (\c[4] [1]));
  DFSH \c_reg[5][2] (.C (clk), .D (n_359), .Q (\c[5] [2]));
  DFSH \c_reg[6][0] (.C (clk), .D (n_358), .Q (\c[6] [0]));
  DFSH \c_reg[5][1] (.C (clk), .D (n_362), .Q (\c[5] [1]));
  DFSH \c_reg[5][0] (.C (clk), .D (n_363), .Q (\c[5] [0]));
  NOR2XL g14303__5795(.A (n_373), .B (n_479), .O (n_414));
  NOR2XL g14304__7344(.A (n_348), .B (n_479), .O (n_413));
  NOR2XL g14301__1840(.A (n_523), .B (n_479), .O (n_412));
  DFSH \i_reg[3] (.C (clk), .D (n_386), .Q (i[3]));
  DFSH \c_reg[6][2] (.C (clk), .D (n_354), .Q (\c[6] [2]));
  DFSH \c_reg[2][0] (.C (clk), .D (n_395), .Q (\c[2] [0]));
  DFSH \c_reg[2][1] (.C (clk), .D (n_394), .Q (\c[2] [1]));
  DFSH \c_reg[3][1] (.C (clk), .D (n_397), .Q (\c[3] [1]));
  DFSH \c_reg[6][1] (.C (clk), .D (n_357), .Q (\c[6] [1]));
  DFSH \c_reg[7][1] (.C (clk), .D (n_350), .Q (\c[7] [1]));
  DFSH \c_reg[3][0] (.C (clk), .D (n_391), .Q (\c[3] [0]));
  DFSH \c_reg[1][0] (.C (clk), .D (n_388), .Q (\c[1] [0]));
  INV g14309(.A (n_411), .O (n_483));
  DFSH \c_reg[4][2] (.C (clk), .D (n_365), .Q (\c[4] [2]));
  DFSH \i_reg[1] (.C (clk), .D (n_396), .Q (i[1]));
  DFSH \i_reg[2] (.C (clk), .D (n_372), .Q (i[2]));
  NOR2XL g14292__5019(.A (n_346), .B (n_479), .O (n_410));
  NOR2XL g14291__1857(.A (n_345), .B (n_479), .O (n_409));
  AND22OXL g14290__9906(.A (n_407), .B (n_404), .C (n_403), .D
       (\array[7] [2]), .O (n_408));
  NOR2XL g14293__8780(.A (n_347), .B (n_479), .O (n_406));
  AND22OXL g14298__4296(.A (n_468), .B (n_404), .C (n_403), .D
       (\array[7] [1]), .O (n_405));
  AND32OXL g14317__3772(.A (n_290), .B (n_384), .C (n_287), .D
       (swp_cnt[7]), .E (n_437), .O (n_402));
  AND22OXL g14305__1474(.A (n_449), .B (n_404), .C (n_403), .D
       (\array[7] [0]), .O (n_401));
  NAND2 g14327__4547(.A (n_400), .B (n_314), .O (n_411));
  NAND2 g14324__9682(.A (n_339), .B (n_400), .O (n_443));
  AND2 g14328__2683(.A (n_400), .B (n_87), .O (n_451));
  HADD g14269__1309(.A (swp_cnt[14]), .B (n_320), .S (n_399), .C
       (n_398));
  OR22AXL g14316__6877(.A (n_393), .B (n_389), .C (n_327), .D (n_479),
       .O (n_397));
  OR2N1A g14312__2900(.A (n_371), .B (i[1]), .C (n_334), .O (n_396));
  OR22AXL g14313__2391(.A (n_390), .B (n_392), .C (n_323), .D (n_479),
       .O (n_395));
  OR22AXL g14314__7675(.A (n_393), .B (n_392), .C (n_325), .D (n_479),
       .O (n_394));
  OR22AXL g14315__7118(.A (n_390), .B (n_389), .C (n_326), .D (n_479),
       .O (n_391));
  OR21AXL g14311__8757(.A (n_332), .B (n_479), .C (n_387), .O (n_388));
  INV g14335(.A (n_343), .O (n_386));
  MUX21XL g14336__1786(.A (n_191), .B (swp_cnt[4]), .SA (n_384), .O
       (n_385));
  MUX21XL g14337__5953(.A (n_255), .B (swp_cnt[5]), .SA (n_384), .O
       (n_383));
  MUX21XL g14338__5703(.A (n_278), .B (swp_cnt[6]), .SA (n_384), .O
       (n_382));
  MUX21XL g14339__7114(.A (n_296), .B (swp_cnt[8]), .SA (n_384), .O
       (n_381));
  INV g14308(.A (n_380), .O (n_484));
  INV g14310(.A (n_379), .O (n_429));
  OR21AXL g14333__5266(.A (n_196), .B (n_479), .C (n_378), .O (n_425));
  OR21AXL g14322__2250(.A (n_206), .B (n_479), .C (n_378), .O (n_457));
  NOR2XL g14329__6083(.A (n_377), .B (n_315), .O (n_424));
  NOR2XL g14330__2703(.A (n_377), .B (n_312), .O (n_463));
  NOR2XL g14331__5795(.A (n_377), .B (n_313), .O (n_459));
  OR21AXL g14334__7344(.A (n_197), .B (n_479), .C (n_333), .O (n_464));
  MUX21XL g14340__1840(.A (n_298), .B (swp_cnt[9]), .SA (n_384), .O
       (n_376));
  MUX21XL g14341__5019(.A (n_304), .B (swp_cnt[10]), .SA (n_384), .O
       (n_375));
  MUX21XL g14342__1857(.A (n_308), .B (swp_cnt[12]), .SA (n_384), .O
       (n_374));
  MUX21XL g14343__9906(.A (n_321), .B (swp_cnt[13]), .SA (n_384), .O
       (n_373));
  OR2N2AXL g14344__8780(.A (i[2]), .B (n_371), .C (n_324), .D (n_107),
       .O (n_372));
  OR2N2AXL g14345__4296(.A (\c[7] [2]), .B (n_352), .C (n_351), .D
       (n_364), .O (n_370));
  OR2N2AXL g14346__3772(.A (\c[4] [0]), .B (n_367), .C (n_366), .D
       (n_390), .O (n_369));
  OR2N2AXL g14347__1474(.A (\c[4] [1]), .B (n_367), .C (n_366), .D
       (n_393), .O (n_368));
  OR2N2AXL g14348__4547(.A (\c[4] [2]), .B (n_367), .C (n_366), .D
       (n_364), .O (n_365));
  OR2N2AXL g14349__9682(.A (\c[5] [0]), .B (n_361), .C (n_360), .D
       (n_390), .O (n_363));
  OR2N2AXL g14350__2683(.A (\c[5] [1]), .B (n_361), .C (n_360), .D
       (n_393), .O (n_362));
  OR2N2AXL g14351__1309(.A (\c[5] [2]), .B (n_361), .C (n_360), .D
       (n_364), .O (n_359));
  OR2N2AXL g14352__6877(.A (\c[6] [0]), .B (n_356), .C (n_355), .D
       (n_390), .O (n_358));
  OR2N2AXL g14353__2900(.A (\c[6] [1]), .B (n_356), .C (n_355), .D
       (n_393), .O (n_357));
  OR2N2AXL g14354__2391(.A (\c[6] [2]), .B (n_356), .C (n_355), .D
       (n_364), .O (n_354));
  OR2N2AXL g14355__7675(.A (\c[7] [0]), .B (n_352), .C (n_351), .D
       (n_390), .O (n_353));
  OR2N2AXL g14356__7118(.A (\c[7] [1]), .B (n_352), .C (n_351), .D
       (n_393), .O (n_350));
  EXNORXL g14359__1786(.A (swp_cnt[0]), .B (n_384), .O (n_348));
  DFMH \i_reg[0] (.C (clk), .D0 (n_342), .D1 (n_371), .S1 (i[0]), .Q
       (i[0]));
  MUX21XL g14320__5953(.A (swp_cnt[3]), .B (n_165), .SA (n_437), .O
       (n_347));
  MUX21XL g14319__5703(.A (swp_cnt[2]), .B (n_123), .SA (n_437), .O
       (n_346));
  MUX21XL g14318__7114(.A (swp_cnt[1]), .B (n_50), .SA (n_437), .O
       (n_345));
  AND21OXL g14332__5266(.A (n_547), .B (n_427), .C (n_344), .O (n_379));
  AND21OXL g14321__2250(.A (n_215), .B (n_427), .C (n_344), .O (n_380));
  AND22OXL g14357__6083(.A (n_342), .B (n_337), .C (n_371), .D (i[3]),
       .O (n_343));
  INV g14360(.A (n_485), .O (n_341));
  INV g14361(.A (n_430), .O (n_340));
  OR21AXL g14373__2703(.A (n_339), .B (n_479), .C (n_338), .O (n_444));
  OR21AXL g14374__5795(.A (n_208), .B (n_479), .C (n_338), .O (n_452));
  INV g14362(.A (n_377), .O (n_400));
  NOR2XL g14364__7344(.A (n_336), .B (n_328), .O (n_485));
  NOR2ANXL g14363__1840(.A (n_337), .B (n_335), .O (n_404));
  NOR3ANXL g14326__5019(.A (n_330), .B (n_318), .C (n_188), .O (n_458));
  NOR2XL g14366__1857(.A (n_336), .B (n_210), .O (n_430));
  NAND2AN g14367__9906(.A (n_335), .B (en), .O (n_377));
  OR21AXL g14369__8780(.A (n_183), .B (n_52), .C (n_342), .O (n_334));
  INV g14368(.A (n_344), .O (n_333));
  AND21OXL g14370__4296(.A (n_207), .B (n_427), .C (n_331), .O (n_378));
  INV g14376(.A (n_431), .O (n_387));
  NOR2XL g14371__3772(.A (n_336), .B (n_329), .O (n_465));
  NAND2 g14379__1474(.A (n_322), .B (\c[1] [0]), .O (n_332));
  INV g14375(.A (n_331), .O (n_338));
  DFSH ready_reg(.C (clk), .D (n_311), .Q (ready_1083));
  NAND3 g14325__4547(.A (n_330), .B (n_213), .C (n_329), .O (n_474));
  AND2 g14396__9682(.A (n_366), .B (n_427), .O (n_367));
  AND21OXL g14372__2683(.A (n_319), .B (i[0]), .C (n_479), .O (n_344));
  NAND3 g14323__1309(.A (n_330), .B (n_328), .C (n_225), .O (n_494));
  INV2 g14377(.A (n_437), .O (n_384));
  NAND2 g14383__6877(.A (n_389), .B (\c[3] [1]), .O (n_327));
  NAND2 g14382__2900(.A (n_389), .B (\c[3] [0]), .O (n_326));
  NAND2 g14381__2391(.A (n_392), .B (\c[2] [1]), .O (n_325));
  INV g14388(.A (n_342), .O (n_324));
  NAND2 g14380__7675(.A (n_392), .B (\c[2] [0]), .O (n_323));
  AND2 g14393__7118(.A (n_351), .B (n_427), .O (n_352));
  AND2 g14391__8757(.A (n_360), .B (n_427), .O (n_361));
  AND2 g14392__1786(.A (n_355), .B (n_427), .O (n_356));
  NOR2XL g14386__5953(.A (n_322), .B (n_390), .O (n_431));
  HADD g14378__5703(.A (swp_cnt[13]), .B (n_307), .S (n_321), .C
       (n_320));
  NAND2 g14384__7114(.A (n_319), .B (resn), .O (n_335));
  NAND4 g14395__5266(.A (n_279), .B (n_317), .C (i[0]), .D (n_281), .O
       (n_336));
  AND3 g14397__2250(.A (n_318), .B (n_317), .C (n_427), .O (n_342));
  NOR2XL g14385__6083(.A (n_319), .B (n_479), .O (n_331));
  NAND2 g14390__2703(.A (n_319), .B (n_337), .O (n_403));
  NAND2 g14398__5795(.A (n_317), .B (n_140), .O (n_322));
  NAND2AN g14399__7344(.A (n_315), .B (n_317), .O (n_392));
  NAND2 g14400__1840(.A (n_317), .B (n_314), .O (n_389));
  NAND2AN g14402__5019(.A (n_313), .B (n_317), .O (n_355));
  NAND2AN g14403__1857(.A (n_312), .B (n_317), .O (n_360));
  AND2N1OXL g14389__9906(.A (n_306), .B (ready_1083), .C (n_479), .O
       (n_311));
  NOR3XL g14394__8780(.A (n_186), .B (n_310), .C (n_479), .O (n_330));
  NAND2 g14404__4296(.A (n_317), .B (n_145), .O (n_366));
  NAND2 g14406__3772(.A (n_317), .B (n_337), .O (n_351));
  NOR2XL g14405__1474(.A (n_317), .B (n_479), .O (n_371));
  NOR2 g14401__4547(.A (n_318), .B (n_310), .O (n_319));
  INV g14408(.A (n_310), .O (n_317));
  HADD g14411__2683(.A (swp_cnt[12]), .B (n_302), .S (n_308), .C
       (n_307));
  NAND2AN g14410__1309(.A (i[3]), .B (n_305), .O (n_310));
  HADD g14413__6877(.A (swp_cnt[10]), .B (n_301), .S (n_304), .C
       (n_303));
  AND211OXL g14412__2900(.A (n_292), .B (n_299), .C (n_105), .D
       (n_300), .O (n_305));
  NOR2ANXL g14416__2391(.A (n_301), .B (n_293), .O (n_302));
  OR2N1A g14414__7675(.A (n_100), .B (n_299), .C (n_297), .O (n_300));
  HADD g14417__7118(.A (swp_cnt[9]), .B (n_295), .S (n_298), .C
       (n_301));
  OR31AXL g14415__8757(.A (n_294), .B (swp_cnt[14]), .C (swp_cnt[13]),
       .D (swp_cnt[15]), .O (n_297));
  HADD g14419__1786(.A (swp_cnt[8]), .B (n_288), .S (n_296), .C
       (n_295));
  DFSH \stepcount_reg[7] (.C (clk), .D (n_289), .Q (stepcount[7]));
  NOR3ANXL g14418__5953(.A (swp_cnt[12]), .B (n_291), .C (n_293), .O
       (n_294));
  AND211OXL g14429__5703(.A (n_99), .B (sel[12]), .C (n_98), .D
       (n_285), .O (n_292));
  AND21OXL g14420__7114(.A (n_290), .B (swp_cnt[8]), .C (swp_cnt[9]),
       .O (n_291));
  NOR2XL g14424__5266(.A (n_525), .B (n_283), .O (n_289));
  DFSH \stepcount_reg[6] (.C (clk), .D (n_284), .Q (stepcount[6]));
  INV g14423(.A (n_287), .O (n_288));
  AND221OXL g14435__6083(.A (n_59), .B (swp_cnt[11]), .C (n_273), .D
       (n_147), .E (n_148), .O (n_285));
  OR2 g14422__2703(.A (n_282), .B (swp_cnt[7]), .O (n_290));
  DFSH \waitcount_reg[4] (.C (clk), .D (n_527), .Q (waitcount[4]));
  NOR2XL g14432__5795(.A (n_276), .B (n_283), .O (n_284));
  NAND2 g14425__7344(.A (n_282), .B (swp_cnt[7]), .O (n_287));
  NAND3 g14442__1840(.A (n_280), .B (n_256), .C (n_281), .O (n_393));
  DFSH \cout_r_reg[0] (.C (clk), .D (n_272), .Q (cout_r[0]));
  OR2N1A g14456__5019(.A (n_280), .B (n_329), .C (n_281), .O (n_364));
  NAND2AN g14461__1857(.A (n_279), .B (n_281), .O (n_390));
  HADD g14426__9906(.A (swp_cnt[6]), .B (n_254), .S (n_278), .C
       (n_282));
  MUX21XL g14437__4296(.A (stepcount[6]), .B (n_260), .SA (n_275), .O
       (n_276));
  DFSH \cout_r_reg[5] (.C (clk), .D (n_541), .Q (cout_r[5]));
  DFSH \cout_r_reg[1] (.C (clk), .D (n_540), .Q (cout_r[1]));
  DFSH \stepcount_reg[5] (.C (clk), .D (n_270), .Q (stepcount[5]));
  DFSH \waitcount_reg[3] (.C (clk), .D (n_268), .Q (waitcount[3]));
  AND211OXL g14455__1474(.A (n_95), .B (sel[8]), .C (n_94), .D (n_258),
       .O (n_273));
  DFSH \cout_r_reg[6] (.C (clk), .D (n_544), .Q (cout_r[6]));
  DFSH \cout_r_reg[7] (.C (clk), .D (n_545), .Q (cout_r[7]));
  INV g14452(.A (n_407), .O (n_435));
  DFSH \cout_r_reg[2] (.C (clk), .D (n_539), .Q (cout_r[2]));
  DFSH \cout_r_reg[4] (.C (clk), .D (n_542), .Q (cout_r[4]));
  DFSH \cout_r_reg[3] (.C (clk), .D (n_543), .Q (cout_r[3]));
  NAND3 g14460__4547(.A (n_240), .B (n_238), .C (n_241), .O (n_407));
  NAND3 g14458__9682(.A (n_253), .B (n_235), .C (n_248), .O (n_449));
  AND2 g14463__2683(.A (n_551), .B (resn), .O (n_272));
  NAND3 g14459__1309(.A (n_251), .B (n_232), .C (n_245), .O (n_468));
  NOR2 g14467__6877(.A (n_318), .B (n_479), .O (n_281));
  NOR2XL g14454__2900(.A (n_252), .B (n_283), .O (n_270));
  NOR2XL g14434__7675(.A (n_247), .B (n_283), .O (n_268));
  HADD g14443__2250(.A (stepcount[6]), .B (n_218), .S (n_260), .C
       (n_259));
  AND222OXL g14479__6083(.A (swp_cnt[7]), .B (n_31), .C (swp_cnt[6]),
       .D (n_67), .E (n_192), .F (n_68), .O (n_258));
  AND2N1OXL g14483__5795(.A (n_256), .B (n_86), .C (n_226), .O (n_318));
  HADD g14439__7344(.A (swp_cnt[5]), .B (n_190), .S (n_255), .C
       (n_254));
  AND22OXL g14477__1840(.A (n_250), .B (\array[1] [0]), .C (n_249), .D
       (\array[5] [0]), .O (n_253));
  MUX21XL g14473__5019(.A (stepcount[5]), .B (n_219), .SA (n_275), .O
       (n_252));
  AND22OXL g14475__1857(.A (n_250), .B (\array[1] [1]), .C (n_249), .D
       (\array[5] [1]), .O (n_251));
  AND222OXL g14476__9906(.A (n_244), .B (\array[2] [0]), .C (n_243), .D
       (\array[3] [0]), .E (n_242), .F (\array[4] [0]), .O (n_248));
  MUX21XL g14441__8780(.A (waitcount[3]), .B (n_221), .SA (n_246), .O
       (n_247));
  AND222OXL g14478__4296(.A (n_244), .B (\array[2] [1]), .C (n_243), .D
       (\array[3] [1]), .E (n_242), .F (\array[4] [1]), .O (n_245));
  AND222OXL g14480__3772(.A (n_244), .B (\array[2] [2]), .C (n_243), .D
       (\array[3] [2]), .E (n_242), .F (\array[4] [2]), .O (n_241));
  AND22OXL g14481__1474(.A (n_250), .B (\array[1] [2]), .C (n_249), .D
       (\array[5] [2]), .O (n_240));
  DFSH \waitcount_reg[2] (.C (clk), .D (n_224), .Q (waitcount[2]));
  DFSH \stepcount_reg[4] (.C (clk), .D (n_223), .Q (stepcount[4]));
  AND22OXL g14485__4547(.A (n_234), .B (\array[0] [2]), .C (n_233), .D
       (\array[6] [2]), .O (n_238));
  AND22OXL g14488__9682(.A (n_234), .B (\array[0] [0]), .C (n_233), .D
       (\array[6] [0]), .O (n_235));
  AND22OXL g14489__2683(.A (n_234), .B (\array[0] [1]), .C (n_233), .D
       (\array[6] [1]), .O (n_232));
  DFSH \state_reg[2] (.C (clk), .D (n_193), .Q (state[2]));
  DFSH \state_reg[3] (.C (clk), .D (n_194), .Q (state[3]));
  DFSH \state_reg[1] (.C (clk), .D (n_195), .Q (state[1]));
  OR2N2AXL g14501__6877(.A (i[1]), .B (n_187), .C (n_225), .D (n_214),
       .O (n_226));
  NAND2AN g14498__2900(.A (n_234), .B (i[0]), .O (n_339));
  NOR2XL g14464__2391(.A (n_189), .B (n_283), .O (n_224));
  NOR2XL g14497__7675(.A (n_185), .B (n_283), .O (n_223));
  HADD g14462__8757(.A (waitcount[3]), .B (n_170), .S (n_221), .C
       (n_220));
  HADD g14496__1786(.A (stepcount[5]), .B (n_168), .S (n_219), .C
       (n_218));
  AND21OXL g14514__5953(.A (n_204), .B (n_216), .C (cout_r[3]), .O
       (n_217));
  OR22AXL g14502__5703(.A (n_214), .B (n_243), .C (n_213), .D (i[1]),
       .O (n_215));
  AND21OXL g14504__7114(.A (n_198), .B (n_216), .C (cout_r[2]), .O
       (n_212));
  AND21OXL g14507__2250(.A (n_202), .B (n_216), .C (cout_r[1]), .O
       (n_209));
  AND2 g14500__6083(.A (n_207), .B (n_206), .O (n_208));
  NOR2ANXL g14509__2703(.A (n_279), .B (n_210), .O (n_250));
  NOR2XL g14508__5795(.A (n_256), .B (n_329), .O (n_242));
  NOR2XL g14510__7344(.A (n_210), .B (n_279), .O (n_234));
  AND21OXL g14515__1840(.A (n_204), .B (n_201), .C (cout_r[7]), .O
       (n_205));
  AND21OXL g14517__5019(.A (n_202), .B (n_201), .C (cout_r[5]), .O
       (n_203));
  AND2N1OXL g14518__1857(.A (n_180), .B (n_216), .C (cout_r[4]), .O
       (n_200));
  AND21OXL g14519__9906(.A (n_198), .B (n_201), .C (cout_r[6]), .O
       (n_199));
  AND2N1OXL g14520__8780(.A (n_249), .B (n_131), .C (n_214), .O
       (n_197));
  AND21OXL g14522__4296(.A (n_184), .B (i[2]), .C (n_90), .O (n_196));
  NOR2XL g14525__3772(.A (next_state[1]), .B (n_283), .O (n_195));
  NOR2XL g14526__1474(.A (next_state[3]), .B (n_283), .O (n_194));
  NOR2XL g14536__4547(.A (next_state[2]), .B (n_283), .O (n_193));
  OR221A g14537__9682(.A (n_82), .B (n_166), .C (sel[5]), .D (n_4), .E
       (n_83), .O (n_192));
  HADD g14474__2683(.A (swp_cnt[4]), .B (n_164), .S (n_191), .C
       (n_190));
  MUX21XL g14490__1309(.A (waitcount[2]), .B (n_171), .SA (n_246), .O
       (n_189));
  DFSH \waitcount_reg[1] (.C (clk), .D (n_177), .Q (waitcount[1]));
  DFSH \stepcount_reg[3] (.C (clk), .D (n_176), .Q (stepcount[3]));
  DFSH \stepcount_reg[2] (.C (clk), .D (n_178), .Q (stepcount[2]));
  DFSH \stepcount_reg[0] (.C (clk), .D (n_173), .Q (stepcount[0]));
  INV g14533(.A (n_233), .O (n_188));
  NAND2 g14527__6877(.A (n_186), .B (n_213), .O (n_187));
  MUX21XL g14521__2900(.A (stepcount[4]), .B (n_169), .SA (n_275), .O
       (n_185));
  NOR2XL g14540__2391(.A (n_328), .B (n_184), .O (n_244));
  DFSH \stepcount_reg[1] (.C (clk), .D (n_172), .Q (stepcount[1]));
  DLH \next_state_reg[0] (.EN (n_182), .D (n_150), .Q (next_state[0]),
       .QB (UNCONNECTED));
  OR21AXL g14538__7675(.A (n_279), .B (n_329), .C (n_38), .O (n_206));
  INV g14534(.A (n_243), .O (n_280));
  AND21OXL g14523__7118(.A (n_213), .B (i[0]), .C (n_183), .O (n_207));
  NAND2AN g14539__8757(.A (n_279), .B (n_328), .O (n_256));
  NOR2XL g14541__1786(.A (n_328), .B (n_329), .O (n_233));
  DLH \next_state_reg[2] (.EN (n_182), .D (n_154), .Q (UNCONNECTED0),
       .QB (next_state[2]));
  DLH \next_state_reg[3] (.EN (n_182), .D (n_46), .Q (UNCONNECTED1),
       .QB (next_state[3]));
  DLH \next_state_reg[1] (.EN (n_182), .D (n_155), .Q (UNCONNECTED2),
       .QB (next_state[1]));
  NAND2 g14542__5703(.A (n_328), .B (n_329), .O (n_210));
  NOR2XL g14551__7114(.A (n_158), .B (n_283), .O (n_178));
  NOR2XL g14505__5266(.A (n_162), .B (n_283), .O (n_177));
  NOR2XL g14550__2250(.A (n_159), .B (n_283), .O (n_176));
  NAND2AN g14553__6083(.A (n_279), .B (i[0]), .O (n_186));
  NOR2ANXL g14552__2703(.A (n_175), .B (n_174), .O (n_198));
  NAND2 g14554__5795(.A (n_175), .B (n_174), .O (n_180));
  DFSH \waitcount_reg[0] (.C (clk), .D (n_161), .Q (waitcount[0]));
  AND2 g14543__7344(.A (n_213), .B (n_279), .O (n_243));
  NOR2XL g14560__1840(.A (n_157), .B (n_283), .O (n_173));
  NOR2XL g14561__5019(.A (n_531), .B (n_283), .O (n_172));
  NOR2ANXL g14564__1857(.A (n_174), .B (n_175), .O (n_202));
  NAND2AN g14565__9906(.A (n_279), .B (n_329), .O (n_184));
  NOR2XL g14555__8780(.A (n_175), .B (n_174), .O (n_204));
  INV g14556(.A (n_461), .O (n_473));
  INV g14558(.A (n_469), .O (n_488));
  AND2 g14566__4296(.A (n_279), .B (n_225), .O (n_249));
  INV g14557(.A (n_446), .O (n_471));
  HADD g14503__3772(.A (waitcount[2]), .B (n_138), .S (n_171), .C
       (n_170));
  HADD g14545__1474(.A (stepcount[4]), .B (n_135), .S (n_169), .C
       (n_168));
  NAND3 g14568__4547(.A (n_129), .B (n_146), .C (n_109), .O (n_446));
  NAND3 g14569__9682(.A (n_125), .B (n_143), .C (n_111), .O (n_469));
  NAND3 g14567__2683(.A (n_128), .B (n_144), .C (n_121), .O (n_461));
  INV g14559(.A (n_213), .O (n_328));
  OR222AXL g14589__1309(.A (n_124), .B (n_45), .C (swp_cnt[4]), .D
       (n_81), .E (n_44), .F (swp_cnt[3]), .O (n_166));
  INV g14571(.A (n_216), .O (n_201));
  OR211AXL g14575__6877(.A (n_47), .B (n_120), .C (n_275), .D (n_246),
       .O (n_182));
  HADD g14524__2900(.A (swp_cnt[3]), .B (n_122), .S (n_165), .C
       (n_164));
  MUX21XL g14535__7675(.A (waitcount[1]), .B (n_139), .SA (n_246), .O
       (n_162));
  NOR2XL g14562__7118(.A (n_151), .B (n_283), .O (n_161));
  OR211A g14576__8757(.A (stepcount[0]), .B (n_102), .C (n_112), .D
       (n_160), .O (n_175));
  OR211A g14577__1786(.A (stepcount[0]), .B (n_106), .C (n_113), .D
       (n_160), .O (n_174));
  NAND3 g14570__5953(.A (n_142), .B (n_115), .C (n_119), .O (n_213));
  MUX21XL g14582__5703(.A (n_136), .B (stepcount[3]), .SA (n_160), .O
       (n_159));
  MUX21XL g14581__7114(.A (n_538), .B (stepcount[2]), .SA (n_160), .O
       (n_158));
  EXNORXL g14580__5266(.A (stepcount[0]), .B (n_160), .O (n_157));
  OR211A g14578__6083(.A (stepcount[0]), .B (n_101), .C (n_160), .D
       (n_108), .O (n_216));
  NAND2 g14586__2703(.A (n_141), .B (n_132), .O (n_279));
  MUX21XL g14585__5795(.A (n_153), .B (n_149), .SA (state[1]), .O
       (n_155));
  AND2XL g14590__7344(.A (n_153), .B (n_160), .O (n_154));
  INV g14599(.A (n_225), .O (n_329));
  AND2N2OXL g14583__5019(.A (n_137), .B (n_246), .C (n_246), .D
       (waitcount[0]), .O (n_151));
  NOR2ANXL g14573__1857(.A (n_149), .B (n_117), .O (n_150));
  OR2N2AXL g14591__9906(.A (n_147), .B (n_96), .C (n_60), .D (sel[10]),
       .O (n_148));
  AND22OXL g14592__8780(.A (n_145), .B (\array[4] [2]), .C (n_314), .D
       (\array[3] [2]), .O (n_146));
  AND22OXL g14593__4296(.A (n_145), .B (\array[4] [0]), .C (n_314), .D
       (\array[3] [0]), .O (n_144));
  AND22OXL g14594__3772(.A (n_145), .B (\array[4] [1]), .C (n_314), .D
       (\array[3] [1]), .O (n_143));
  AND22OXL g14595__1474(.A (n_92), .B (\c[2] [1]), .C (n_314), .D
       (\c[3] [1]), .O (n_142));
  AND22OXL g14596__4547(.A (n_140), .B (\c[1] [0]), .C (n_314), .D
       (\c[3] [0]), .O (n_141));
  NAND2 g14605__9682(.A (n_110), .B (n_114), .O (n_225));
  INV g14601(.A (n_160), .O (n_275));
  HADD g14572__2683(.A (waitcount[1]), .B (n_137), .S (n_139), .C
       (n_138));
  HADD g14602__1309(.A (stepcount[3]), .B (n_58), .S (n_136), .C
       (n_135));
  AND2 g14617__6877(.A (n_133), .B (n_130), .O (n_134));
  AND2N2OXL g14597__2900(.A (n_91), .B (n_131), .C (n_88), .D (i[2]),
       .O (n_132));
  AND3 g14607__2391(.A (n_130), .B (state[1]), .C (n_89), .O (n_160));
  AND222OXL g14613__7675(.A (n_127), .B (\array[6] [2]), .C (n_337), .D
       (\array[7] [2]), .E (n_126), .F (\array[2] [2]), .O (n_129));
  AND222OXL g14612__7118(.A (n_127), .B (\array[6] [0]), .C (n_337), .D
       (\array[7] [0]), .E (n_126), .F (\array[2] [0]), .O (n_128));
  AND222OXL g14611__8757(.A (n_127), .B (\array[6] [1]), .C (n_337), .D
       (\array[7] [1]), .E (n_126), .F (\array[2] [1]), .O (n_125));
  AND222OXL g14616__1786(.A (n_40), .B (sel[1]), .C (n_7), .D (n_63),
       .E (n_43), .F (sel[2]), .O (n_124));
  HADD g14587__5953(.A (swp_cnt[2]), .B (n_49), .S (n_123), .C (n_122));
  AND22OXL g14632__5703(.A (n_140), .B (\array[1] [0]), .C (n_118), .D
       (\array[5] [0]), .O (n_121));
  INVXL g14634(.A (n_133), .O (n_120));
  AND22OXL g14630__7114(.A (n_118), .B (\c[5] [1]), .C (n_337), .D
       (\c[7] [1]), .O (n_119));
  MUX21XL g14598__5266(.A (n_104), .B (state[0]), .SA (en), .O (n_117));
  AND22OXL g14631__2250(.A (n_145), .B (\c[4] [1]), .C (n_127), .D
       (\c[6] [1]), .O (n_115));
  NAND4ANXL g14604__6083(.A (n_53), .B (waitcount[0]), .C (ready_1083),
       .D (state[0]), .O (n_149));
  AND22OXL g14629__2703(.A (n_145), .B (\c[4] [2]), .C (n_337), .D
       (\c[7] [2]), .O (n_114));
  NAND3 g14609__5795(.A (n_85), .B (n_76), .C (stepcount[0]), .O
       (n_113));
  NAND3 g14610__7344(.A (n_64), .B (n_72), .C (stepcount[0]), .O
       (n_112));
  AND22OXL g14626__1840(.A (n_140), .B (\array[1] [1]), .C (n_118), .D
       (\array[5] [1]), .O (n_111));
  AND22OXL g14627__5019(.A (n_118), .B (\c[5] [2]), .C (n_127), .D
       (\c[6] [2]), .O (n_110));
  AND22OXL g14628__1857(.A (n_140), .B (\array[1] [2]), .C (n_118), .D
       (\array[5] [2]), .O (n_109));
  NAND3 g14608__9906(.A (n_61), .B (n_84), .C (stepcount[0]), .O
       (n_108));
  HADD g14614__8780(.A (n_214), .B (n_51), .S (n_107), .C (n_314));
  NAND2 g14618__4296(.A (n_80), .B (n_69), .O (n_106));
  OR32AXL g14615__3772(.A (n_56), .B (n_54), .C (sel[14]), .D
       (sel[15]), .E (n_12), .O (n_105));
  NOR4ANXL g14603__1474(.A (n_35), .B (n_57), .C (stepcount[4]), .D
       (stepcount[3]), .O (n_153));
  NOR2XL g14644__4547(.A (state[1]), .B (state[0]), .O (n_133));
  NAND2 g14606__9682(.A (n_104), .B (state[0]), .O (n_246));
  NAND2 g14620__1309(.A (n_77), .B (n_71), .O (n_102));
  NAND2 g14619__6877(.A (n_73), .B (n_70), .O (n_101));
  OR32AXL g14624__2900(.A (n_99), .B (n_98), .C (sel[12]), .D
       (sel[13]), .E (n_15), .O (n_100));
  OR32AXL g14625__2391(.A (n_95), .B (n_94), .C (sel[8]), .D (sel[9]),
       .E (n_10), .O (n_96));
  INV g14655(.A (n_315), .O (n_92));
  AND22OXL g14641__7675(.A (n_126), .B (\c[2] [0]), .C (n_90), .D
       (\c[6] [0]), .O (n_91));
  INV g14668(.A (n_118), .O (n_312));
  INV g14657(.A (state[0]), .O (n_89));
  OR2N2AXL g14633__7118(.A (\c[4] [0]), .B (n_87), .C (n_29), .D
       (n_86), .O (n_88));
  INV g14658(.A (n_127), .O (n_313));
  AND22OXL g14637__8757(.A (n_79), .B (\array[3] [1]), .C (n_78), .D
       (\array[7] [1]), .O (n_85));
  AND22OXL g14638__1786(.A (n_75), .B (\array[1] [2]), .C (n_74), .D
       (\array[5] [2]), .O (n_84));
  NAND3AN g14639__5953(.A (n_82), .B (swp_cnt[4]), .C (n_81), .O
       (n_83));
  AND22OXL g14642__5703(.A (n_79), .B (\array[2] [1]), .C (n_78), .D
       (\array[6] [1]), .O (n_80));
  AND22OXL g14646__7114(.A (n_79), .B (\array[2] [0]), .C (n_78), .D
       (\array[6] [0]), .O (n_77));
  AND22OXL g14647__5266(.A (n_75), .B (\array[1] [1]), .C (n_74), .D
       (\array[5] [1]), .O (n_76));
  AND22OXL g14648__2250(.A (n_79), .B (\array[2] [2]), .C (n_78), .D
       (\array[6] [2]), .O (n_73));
  AND22OXL g14649__6083(.A (n_75), .B (\array[1] [0]), .C (n_74), .D
       (\array[5] [0]), .O (n_72));
  AND22OXL g14650__2703(.A (n_75), .B (\array[0] [0]), .C (n_74), .D
       (\array[4] [0]), .O (n_71));
  AND22OXL g14651__5795(.A (n_75), .B (\array[0] [2]), .C (n_74), .D
       (\array[4] [2]), .O (n_70));
  AND22OXL g14652__7344(.A (n_75), .B (\array[0] [1]), .C (n_74), .D
       (\array[4] [1]), .O (n_69));
  AND21OXL g14671__1840(.A (n_1), .B (sel[6]), .C (n_66), .O (n_68));
  NOR2XL g14660__5019(.A (n_66), .B (sel[6]), .O (n_67));
  AND22OXL g14653__1857(.A (n_79), .B (\array[3] [0]), .C (n_78), .D
       (\array[7] [0]), .O (n_64));
  INV g14654(.A (n_41), .O (n_63));
  MUX21XL g14645__9906(.A (n_79), .B (stepcount[2]), .SA
       (stepcount[0]), .O (n_62));
  AND22OXL g14640__8780(.A (n_79), .B (\array[3] [2]), .C (n_78), .D
       (\array[7] [2]), .O (n_61));
  AND21OXL g14670__4296(.A (swp_cnt[10]), .B (n_59), .C (n_33), .O
       (n_60));
  INV g14656(.A (n_57), .O (n_58));
  AND21OXL g14677__3772(.A (n_56), .B (sel[14]), .C (n_54), .O (n_299));
  AND2 g14623__1474(.A (n_53), .B (waitcount[0]), .O (n_137));
  NAND2 g14661__4547(.A (n_183), .B (n_214), .O (n_315));
  DFSH \state_reg[0] (.C (clk), .D (n_28), .Q (state[0]));
  AND2 g14663__9682(.A (n_52), .B (n_214), .O (n_140));
  AND2 g14678__2683(.A (n_52), .B (i[2]), .O (n_118));
  AND2 g14666__1309(.A (n_183), .B (i[2]), .O (n_127));
  AND2 g14667__6877(.A (n_51), .B (i[2]), .O (n_337));
  HADD g14635__2900(.A (swp_cnt[1]), .B (swp_cnt[0]), .S (n_50), .C
       (n_49));
  HADD g14636__2391(.A (state[3]), .B (state[2]), .S (n_48), .C (n_47));
  OR2N1AXL g14673__7675(.A (state[3]), .B (en), .C (n_8), .O (n_46));
  OR2N2AXL g14672__7118(.A (n_44), .B (swp_cnt[3]), .C (n_43), .D
       (sel[2]), .O (n_45));
  OR21AXL g14659__8757(.A (n_40), .B (sel[1]), .C (sel[0]), .O (n_41));
  INV g14689(.A (n_90), .O (n_38));
  AND2N2OXL g14676__1786(.A (swp_cnt[11]), .B (n_59), .C (n_0), .D
       (sel[10]), .O (n_147));
  NAND2 g14662__5953(.A (n_78), .B (stepcount[0]), .O (n_57));
  NOR2ANXL g14622__5703(.A (n_130), .B (state[1]), .O (n_104));
  AND2 g14665__7114(.A (n_87), .B (i[2]), .O (n_145));
  INV2 g14691(.A (n_36), .O (n_427));
  BF3 g14693(.A (n_36), .O (n_479));
  NOR3XL g14675__5266(.A (stepcount[7]), .B (stepcount[5]), .C
       (stepcount[6]), .O (n_35));
  INV g14688(.A (n_293), .O (n_33));
  NOR2ANXL g14695__6083(.A (sel[5]), .B (swp_cnt[5]), .O (n_82));
  NOR2XL g14696__2703(.A (swp_cnt[7]), .B (n_31), .O (n_66));
  NOR2ANXL g14697__5795(.A (sel[9]), .B (swp_cnt[9]), .O (n_94));
  NAND4 g14643__7344(.A (waitcount[4]), .B (waitcount[2]), .C
       (waitcount[3]), .D (waitcount[1]), .O (n_53));
  NOR2XL g14700__1840(.A (n_214), .B (i[0]), .O (n_90));
  MUX21XL g14674__5019(.A (\c[7] [0]), .B (\c[5] [0]), .SA (i[1]), .O
       (n_29));
  AND2XL g14694__1857(.A (resn), .B (next_state[0]), .O (n_28));
  NOR2ANXL g14698__9906(.A (sel[13]), .B (swp_cnt[13]), .O (n_98));
  NOR2XL g14680__8780(.A (n_86), .B (n_131), .O (n_51));
  NOR2ANXL g14679__4296(.A (sel[15]), .B (swp_cnt[15]), .O (n_54));
  NAND2XL g14703__3772(.A (en), .B (resn), .O (n_36));
  NOR2XL g14682__1474(.A (n_86), .B (i[1]), .O (n_52));
  NOR2XL g14701__4547(.A (n_131), .B (i[0]), .O (n_183));
  INV4 g14708(.A (n_18), .O (ready));
  NOR2XL g14683__9682(.A (i[0]), .B (i[1]), .O (n_87));
  NOR2 g14685__2683(.A (stepcount[1]), .B (stepcount[2]), .O (n_75));
  NOR2AN g14686__1309(.A (stepcount[1]), .B (stepcount[2]), .O (n_79));
  NOR2AN g14702__6877(.A (stepcount[2]), .B (stepcount[1]), .O (n_74));
  INV2 g14753(.A (resn), .O (n_283));
  NAND2 g14699__2900(.A (swp_cnt[11]), .B (swp_cnt[10]), .O (n_293));
  NOR2XL g14681__2391(.A (state[2]), .B (state[3]), .O (n_130));
  NOR2XL g14684__7675(.A (i[0]), .B (i[2]), .O (n_126));
  AND2 g14687__7118(.A (stepcount[2]), .B (stepcount[1]), .O (n_78));
  INV g14747(.A (swp_cnt[13]), .O (n_15));
  INV g14712(.A (\array[3] [2]), .O (n_14));
  BF4 g14705(.A (cout_r[2]), .O (cout[2]));
  INV g14718(.A (swp_cnt[15]), .O (n_12));
  BF4 g14739(.A (cout_r[4]), .O (cout[4]));
  INV g14719(.A (swp_cnt[9]), .O (n_10));
  INVXL g14709(.A (ready_1083), .O (n_18));
  INVXL g14722(.A (sel[3]), .O (n_44));
  INV g14716(.A (swp_cnt[1]), .O (n_40));
  INVXL g14731(.A (sel[4]), .O (n_81));
  BF4 g14742(.A (cout_r[6]), .O (cout[6]));
  INVXL g14723(.A (sel[7]), .O (n_31));
  BF4 g14738(.A (cout_r[5]), .O (cout[5]));
  INV g14751(.A (i[0]), .O (n_86));
  INV g14750(.A (i[1]), .O (n_131));
  INV g14752(.A (i[2]), .O (n_214));
  INVXL g14713(.A (state[2]), .O (n_8));
  INV g14715(.A (swp_cnt[0]), .O (n_7));
  INV g14711(.A (\array[1] [2]), .O (n_6));
  BF4 g14704(.A (cout_r[3]), .O (cout[3]));
  INV g14743(.A (swp_cnt[5]), .O (n_4));
  BF4 g14710(.A (cout_r[1]), .O (cout[1]));
  BF4 g14706(.A (cout_r[0]), .O (cout[0]));
  INV g14744(.A (swp_cnt[6]), .O (n_1));
  INV g14746(.A (swp_cnt[10]), .O (n_0));
  INV g14748(.A (swp_cnt[14]), .O (n_56));
  BF4 g14736(.A (cout_r[7]), .O (cout[7]));
  INV g14717(.A (swp_cnt[8]), .O (n_95));
  INV g14745(.A (swp_cnt[12]), .O (n_99));
  INV g14714(.A (swp_cnt[2]), .O (n_43));
  INVXL g14740(.A (sel[11]), .O (n_59));
  INVXL g14853(.A (n_305), .O (n_306));
  INV g14854(.A (n_319), .O (n_437));
  EXNORXL g2(.A (n_520), .B (swp_cnt[15]), .O (n_521));
  NOR2ANXL g3(.A (n_398), .B (n_437), .O (n_520));
  EXNORXL g14855(.A (n_522), .B (swp_cnt[11]), .O (n_523));
  AND2 g14856(.A (n_303), .B (n_384), .O (n_522));
  EXNORXL g14857(.A (n_524), .B (stepcount[7]), .O (n_525));
  NOR2ANXL g14858(.A (n_259), .B (n_275), .O (n_524));
  AND2N1OXL g14859(.A (n_526), .B (waitcount[4]), .C (n_283), .O
       (n_527));
  NOR2ANXL g14860(.A (n_220), .B (n_246), .O (n_526));
  EXNORXL g14863(.A (n_530), .B (stepcount[1]), .O (n_531));
  AND2 g14864(.A (stepcount[0]), .B (n_160), .O (n_530));
  BF4 drc_bufs(.A (n_134), .O (init));
  BF4 drc_bufs14867(.A (n_549), .O (amp_enable));
  NAND2AN g14870(.A (n_74), .B (n_62), .O (n_538));
  NOR2ANXL g14871(.A (resn), .B (n_212), .O (n_539));
  NOR2ANXL g14872(.A (resn), .B (n_209), .O (n_540));
  NOR2ANXL g14873(.A (resn), .B (n_203), .O (n_541));
  NOR2ANXL g14874(.A (resn), .B (n_200), .O (n_542));
  NOR2ANXL g14875(.A (resn), .B (n_217), .O (n_543));
  NOR2ANXL g14876(.A (resn), .B (n_199), .O (n_544));
  NOR2ANXL g14877(.A (resn), .B (n_205), .O (n_545));
  OR2 g14878(.A (n_546), .B (n_210), .O (n_547));
  AND2N1OXL g14879(.A (i[2]), .B (i[1]), .C (n_279), .O (n_546));
  NAND3 g14880(.A (n_548), .B (n_246), .C (n_275), .O (n_549));
  NAND2 g14881(.A (n_48), .B (n_133), .O (n_548));
  OR2 g14882(.A (n_550), .B (cout_r[0]), .O (n_551));
  NOR3ANXL g14883(.A (n_216), .B (n_275), .C (n_180), .O (n_550));
endmodule

