# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {Vivado 12-172}  -string {{ERROR: [Vivado 12-172] File or Directory 'U:/vivado_ws/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/blk_mem_gen_0/raifes_gpio_test2.coe' does not exist}}  -suppress 
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.cache/wt [current_project]
set_property parent.project_path D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/13_Projekte/fpga/NexysVideo/ipproj1/ipproj1.ip_user_files [current_project]
update_ip_catalog
set_property ip_output_repo d:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/blk_mem_gen_0/raifes_gpio_SWtoLED.coe
add_files D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/blk_mem_gen_0/LED_toggle.coe
add_files D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/blk_mem_gen_0/SWtoLED_withmem.coe
add_files D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/blk_mem_gen_0/SWtoLED_withbranchcounter.coe
add_files D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/blk_mem_gen_0/blt.coe
add_files D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/blk_mem_gen_0/uart_test1.coe
add_files D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/blk_mem_gen_0/uart_test2.coe
add_files D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/blk_mem_gen_0/princetest.coe
add_files D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/blk_mem_gen_0/multest.coe
add_files D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/blk_mem_gen_0/prince_katan_test.coe
read_verilog {
  D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/imports/src/raifes_platform_constants.vh
  D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/imports/src/raifes_hasti_constants.vh
  D:/13_Projekte/src/raifes_ctrl_constants.vh
  D:/13_Projekte/src/rv32_opcodes.vh
  D:/13_Projekte/src/raifes_arch_options.vh
  D:/13_Projekte/src/raifes_alu_ops.vh
  D:/13_Projekte/src/modules/raifes_cop/raifes_cop_common.vh
  D:/13_Projekte/src/modules/raifes_cop/ise_decode.v
  D:/13_Projekte/src/raifes_platform_constants.vh
  D:/13_Projekte/src/raifes_hasti_constants.vh
  D:/13_Projekte/src/raifes_csr_addr_map.vh
  D:/13_Projekte/src/raifes_dmi_constants.vh
  D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/imports/src/raifes_ctrl_constants.vh
  D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/imports/src/raifes_csr_addr_map.vh
  D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/imports/src/raifes_dmi_constants.vh
}
set_property file_type "Verilog Header" [get_files D:/13_Projekte/src/modules/raifes_cop/ise_decode.v]
read_verilog -library xil_defaultlib {
  D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/new/UART_module.v
  D:/13_Projekte/src/modules/raifes_cop/integ_raifes_rcpi2cop.v
  D:/13_Projekte/src/raifes_PC_mux.v
  D:/13_Projekte/src/raifes_alu.v
  D:/13_Projekte/src/modules/raifes_cop/raifes_cop_cprs.v
  D:/13_Projekte/src/modules/raifes_cop/raifes_cop_idecode.v
  D:/13_Projekte/src/modules/raifes_cop/raifes_cop_malu.v
  D:/13_Projekte/src/modules/raifes_cop/raifes_cop_mem.v
  D:/13_Projekte/src/modules/raifes_cop/raifes_cop_palu.v
  D:/13_Projekte/src/modules/raifes_cop/raifes_cop_palu_adder.v
  D:/13_Projekte/src/modules/raifes_cop/raifes_cop_palu_multiplier.v
  D:/13_Projekte/src/modules/raifes_cop/raifes_cop_palu_shifter.v
  D:/13_Projekte/src/modules/raifes_cop/raifes_cop_permute.v
  D:/13_Projekte/src/modules/raifes_cop/raifes_cop_rng.v
  D:/13_Projekte/src/modules/raifes_cop/raifes_cop_top.v
  D:/13_Projekte/src/raifes_core.v
  D:/13_Projekte/src/raifes_csr_file.v
  D:/13_Projekte/src/raifes_ctrl.v
  D:/13_Projekte/src/raifes_debug_module.v
  D:/13_Projekte/src/raifes_debug_rom.v
  D:/13_Projekte/src/raifes_dtm.v
  D:/13_Projekte/src/modules/raifes_gpio/src/raifes_gpio.v
  D:/13_Projekte/src/raifes_hasti_bridge.v
  D:/13_Projekte/src/raifes_imm_gen.v
  D:/13_Projekte/src/raifes_mul_div.v
  D:/13_Projekte/src/raifes_pipeline.v
  D:/13_Projekte/src/raifes_regfile.v
  D:/13_Projekte/src/raifes_src_a_mux.v
  D:/13_Projekte/src/raifes_src_b_mux.v
  D:/13_Projekte/src/raifes_sync_to_hasti_bridge.v
  D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/imports/src/raifes_top.v
  D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/imports/src/raifes_uart.v
  D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/imports/src/raifes_fpga_wrapper.v
}
read_ip -quiet D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/constrs_1/imports/digilent-xdc-master/Nexys-Video-Master.xdc
set_property used_in_implementation false [get_files D:/13_Projekte/fpga/NexysVideo/raifes_fpga_bram/raifes_fpga_bram.srcs/constrs_1/imports/digilent-xdc-master/Nexys-Video-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top raifes_fpga_wrapper -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef raifes_fpga_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file raifes_fpga_wrapper_utilization_synth.rpt -pb raifes_fpga_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
