webtalk_init -webtalk_dir U:/vivado_ws/raifes_fpga_version1/raifes_fpga_version1.sim/sim_1/behav/xsim/xsim.dir/raifes_top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 27 14:55:00 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4e5d048e-c40a-4f82-84aa-75789341b3fa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b1214aecb5834bdfb4d38f6d4b7eee7e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Athlon(tm) II X2 250 Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "18330330 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "198.87_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "2026304_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3244646274 -regid "" -xml U:/vivado_ws/raifes_fpga_version1/raifes_fpga_version1.sim/sim_1/behav/xsim/xsim.dir/raifes_top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html U:/vivado_ws/raifes_fpga_version1/raifes_fpga_version1.sim/sim_1/behav/xsim/xsim.dir/raifes_top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm U:/vivado_ws/raifes_fpga_version1/raifes_fpga_version1.sim/sim_1/behav/xsim/xsim.dir/raifes_top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
