set_db port:permut_sel_aio/clk .original_name {clk}
set_db port:permut_sel_aio/resn .original_name {resn}
set_db port:permut_sel_aio/en .original_name {en}
set_db {port:permut_sel_aio/sel[15]} .original_name {sel[15]}
set_db {port:permut_sel_aio/sel[14]} .original_name {sel[14]}
set_db {port:permut_sel_aio/sel[13]} .original_name {sel[13]}
set_db {port:permut_sel_aio/sel[12]} .original_name {sel[12]}
set_db {port:permut_sel_aio/sel[11]} .original_name {sel[11]}
set_db {port:permut_sel_aio/sel[10]} .original_name {sel[10]}
set_db {port:permut_sel_aio/sel[9]} .original_name {sel[9]}
set_db {port:permut_sel_aio/sel[8]} .original_name {sel[8]}
set_db {port:permut_sel_aio/sel[7]} .original_name {sel[7]}
set_db {port:permut_sel_aio/sel[6]} .original_name {sel[6]}
set_db {port:permut_sel_aio/sel[5]} .original_name {sel[5]}
set_db {port:permut_sel_aio/sel[4]} .original_name {sel[4]}
set_db {port:permut_sel_aio/sel[3]} .original_name {sel[3]}
set_db {port:permut_sel_aio/sel[2]} .original_name {sel[2]}
set_db {port:permut_sel_aio/sel[1]} .original_name {sel[1]}
set_db {port:permut_sel_aio/sel[0]} .original_name {sel[0]}
set_db port:permut_sel_aio/ready .original_name {ready}
set_db port:permut_sel_aio/init .original_name {init}
set_db port:permut_sel_aio/amp_enable .original_name {amp_enable}
set_db {port:permut_sel_aio/cout[7]} .original_name {cout[7]}
set_db {port:permut_sel_aio/cout[6]} .original_name {cout[6]}
set_db {port:permut_sel_aio/cout[5]} .original_name {cout[5]}
set_db {port:permut_sel_aio/cout[4]} .original_name {cout[4]}
set_db {port:permut_sel_aio/cout[3]} .original_name {cout[3]}
set_db {port:permut_sel_aio/cout[2]} .original_name {cout[2]}
set_db {port:permut_sel_aio/cout[1]} .original_name {cout[1]}
set_db {port:permut_sel_aio/cout[0]} .original_name {cout[0]}



set_db {pin:permut_sel_aio/swp_cnt_reg[15]/Q} .original_name {swp_cnt[15]/q}
set_db {pin:permut_sel_aio/array_reg[3][1]/Q} .original_name {array[3][1]/q}
set_db {pin:permut_sel_aio/array_reg[3][0]/Q} .original_name {array[3][0]/q}
set_db {pin:permut_sel_aio/array_reg[4][2]/Q} .original_name {array[4][2]/q}
set_db {pin:permut_sel_aio/array_reg[5][2]/Q} .original_name {array[5][2]/q}
set_db {pin:permut_sel_aio/array_reg[6][2]/Q} .original_name {array[6][2]/q}
set_db {pin:permut_sel_aio/array_reg[6][1]/Q} .original_name {array[6][1]/q}
set_db {pin:permut_sel_aio/array_reg[2][1]/Q} .original_name {array[2][1]/q}
set_db {pin:permut_sel_aio/array_reg[5][0]/Q} .original_name {array[5][0]/q}
set_db {pin:permut_sel_aio/array_reg[4][0]/Q} .original_name {array[4][0]/q}
set_db {pin:permut_sel_aio/array_reg[4][1]/Q} .original_name {array[4][1]/q}
set_db {pin:permut_sel_aio/array_reg[5][1]/Q} .original_name {array[5][1]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[14]/Q} .original_name {swp_cnt[14]/q}
set_db {pin:permut_sel_aio/array_reg[2][2]/Q} .original_name {array[2][2]/q}
set_db {pin:permut_sel_aio/array_reg[2][0]/Q} .original_name {array[2][0]/q}
set_db {pin:permut_sel_aio/array_reg[6][0]/Q} .original_name {array[6][0]/q}
set_db {pin:permut_sel_aio/array_reg[1][0]/Q} .original_name {array[1][0]/q}
set_db {pin:permut_sel_aio/array_reg[1][1]/Q} .original_name {array[1][1]/q}
set_db {pin:permut_sel_aio/array_reg[3][2]/Q} .original_name {array[3][2]/q}
set_db {pin:permut_sel_aio/array_reg[0][0]/Q} .original_name {array[0][0]/q}
set_db {pin:permut_sel_aio/array_reg[0][1]/Q} .original_name {array[0][1]/q}
set_db {pin:permut_sel_aio/array_reg[0][2]/Q} .original_name {array[0][2]/q}
set_db {pin:permut_sel_aio/array_reg[7][1]/Q} .original_name {array[7][1]/q}
set_db {pin:permut_sel_aio/array_reg[7][2]/Q} .original_name {array[7][2]/q}
set_db {pin:permut_sel_aio/array_reg[7][0]/Q} .original_name {array[7][0]/q}
set_db {pin:permut_sel_aio/array_reg[1][2]/Q} .original_name {array[1][2]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[7]/Q} .original_name {swp_cnt[7]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[0]/Q} .original_name {swp_cnt[0]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[4]/Q} .original_name {swp_cnt[4]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[6]/Q} .original_name {swp_cnt[6]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[5]/Q} .original_name {swp_cnt[5]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[8]/Q} .original_name {swp_cnt[8]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[11]/Q} .original_name {swp_cnt[11]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[9]/Q} .original_name {swp_cnt[9]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[12]/Q} .original_name {swp_cnt[12]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[13]/Q} .original_name {swp_cnt[13]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[10]/Q} .original_name {swp_cnt[10]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[1]/Q} .original_name {swp_cnt[1]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[2]/Q} .original_name {swp_cnt[2]/q}
set_db {pin:permut_sel_aio/swp_cnt_reg[3]/Q} .original_name {swp_cnt[3]/q}
set_db {pin:permut_sel_aio/c_reg[7][2]/Q} .original_name {c[7][2]/q}
set_db {pin:permut_sel_aio/c_reg[7][0]/Q} .original_name {c[7][0]/q}
set_db {pin:permut_sel_aio/c_reg[4][0]/Q} .original_name {c[4][0]/q}
set_db {pin:permut_sel_aio/c_reg[4][1]/Q} .original_name {c[4][1]/q}
set_db {pin:permut_sel_aio/c_reg[5][2]/Q} .original_name {c[5][2]/q}
set_db {pin:permut_sel_aio/c_reg[6][0]/Q} .original_name {c[6][0]/q}
set_db {pin:permut_sel_aio/c_reg[5][1]/Q} .original_name {c[5][1]/q}
set_db {pin:permut_sel_aio/c_reg[5][0]/Q} .original_name {c[5][0]/q}
set_db {pin:permut_sel_aio/i_reg[3]/Q} .original_name {i[3]/q}
set_db {pin:permut_sel_aio/c_reg[6][2]/Q} .original_name {c[6][2]/q}
set_db {pin:permut_sel_aio/c_reg[2][0]/Q} .original_name {c[2][0]/q}
set_db {pin:permut_sel_aio/c_reg[2][1]/Q} .original_name {c[2][1]/q}
set_db {pin:permut_sel_aio/c_reg[3][1]/Q} .original_name {c[3][1]/q}
set_db {pin:permut_sel_aio/c_reg[6][1]/Q} .original_name {c[6][1]/q}
set_db {pin:permut_sel_aio/c_reg[7][1]/Q} .original_name {c[7][1]/q}
set_db {pin:permut_sel_aio/c_reg[3][0]/Q} .original_name {c[3][0]/q}
set_db {pin:permut_sel_aio/c_reg[1][0]/Q} .original_name {c[1][0]/q}
set_db {pin:permut_sel_aio/c_reg[4][2]/Q} .original_name {c[4][2]/q}
set_db {pin:permut_sel_aio/i_reg[1]/Q} .original_name {i[1]/q}
set_db {pin:permut_sel_aio/i_reg[2]/Q} .original_name {i[2]/q}
set_db {pin:permut_sel_aio/i_reg[0]/Q} .original_name {i[0]/q}
set_db pin:permut_sel_aio/ready_reg/Q .original_name {ready/q}
set_db {pin:permut_sel_aio/stepcount_reg[7]/Q} .original_name {stepcount[7]/q}
set_db {pin:permut_sel_aio/stepcount_reg[6]/Q} .original_name {stepcount[6]/q}
set_db {pin:permut_sel_aio/waitcount_reg[4]/Q} .original_name {waitcount[4]/q}
set_db {pin:permut_sel_aio/cout_r_reg[0]/Q} .original_name {cout_r[0]/q}
set_db {pin:permut_sel_aio/cout_r_reg[5]/Q} .original_name {cout_r[5]/q}
set_db {pin:permut_sel_aio/cout_r_reg[1]/Q} .original_name {cout_r[1]/q}
set_db {pin:permut_sel_aio/stepcount_reg[5]/Q} .original_name {stepcount[5]/q}
set_db {pin:permut_sel_aio/waitcount_reg[3]/Q} .original_name {waitcount[3]/q}
set_db {pin:permut_sel_aio/cout_r_reg[6]/Q} .original_name {cout_r[6]/q}
set_db {pin:permut_sel_aio/cout_r_reg[7]/Q} .original_name {cout_r[7]/q}
set_db {pin:permut_sel_aio/cout_r_reg[2]/Q} .original_name {cout_r[2]/q}
set_db {pin:permut_sel_aio/cout_r_reg[4]/Q} .original_name {cout_r[4]/q}
set_db {pin:permut_sel_aio/cout_r_reg[3]/Q} .original_name {cout_r[3]/q}
set_db {pin:permut_sel_aio/waitcount_reg[2]/Q} .original_name {waitcount[2]/q}
set_db {pin:permut_sel_aio/stepcount_reg[4]/Q} .original_name {stepcount[4]/q}
set_db {pin:permut_sel_aio/state_reg[2]/Q} .original_name {state[2]/q}
set_db {pin:permut_sel_aio/state_reg[3]/Q} .original_name {state[3]/q}
set_db {pin:permut_sel_aio/state_reg[1]/Q} .original_name {state[1]/q}
set_db {pin:permut_sel_aio/waitcount_reg[1]/Q} .original_name {waitcount[1]/q}
set_db {pin:permut_sel_aio/stepcount_reg[3]/Q} .original_name {stepcount[3]/q}
set_db {pin:permut_sel_aio/stepcount_reg[2]/Q} .original_name {stepcount[2]/q}
set_db {pin:permut_sel_aio/stepcount_reg[0]/Q} .original_name {stepcount[0]/q}
set_db {pin:permut_sel_aio/stepcount_reg[1]/Q} .original_name {stepcount[1]/q}
set_db {pin:permut_sel_aio/next_state_reg[0]/Q} .original_name {next_state[0]/q}
set_db {pin:permut_sel_aio/next_state_reg[0]/QB} .original_name {next_state[0]/q}
set_db {pin:permut_sel_aio/next_state_reg[2]/Q} .original_name {next_state[2]/q}
set_db {pin:permut_sel_aio/next_state_reg[2]/QB} .original_name {next_state[2]/q}
set_db {pin:permut_sel_aio/next_state_reg[3]/Q} .original_name {next_state[3]/q}
set_db {pin:permut_sel_aio/next_state_reg[3]/QB} .original_name {next_state[3]/q}
set_db {pin:permut_sel_aio/next_state_reg[1]/Q} .original_name {next_state[1]/q}
set_db {pin:permut_sel_aio/next_state_reg[1]/QB} .original_name {next_state[1]/q}
set_db {pin:permut_sel_aio/waitcount_reg[0]/Q} .original_name {waitcount[0]/q}
set_db {pin:permut_sel_aio/state_reg[0]/Q} .original_name {state[0]/q}
