set_db port:raifes_dtm/tck .original_name {tck}
set_db port:raifes_dtm/tms .original_name {tms}
set_db port:raifes_dtm/tdi .original_name {tdi}
set_db {port:raifes_dtm/dmi_rdata[31]} .original_name {dmi_rdata[31]}
set_db {port:raifes_dtm/dmi_rdata[30]} .original_name {dmi_rdata[30]}
set_db {port:raifes_dtm/dmi_rdata[29]} .original_name {dmi_rdata[29]}
set_db {port:raifes_dtm/dmi_rdata[28]} .original_name {dmi_rdata[28]}
set_db {port:raifes_dtm/dmi_rdata[27]} .original_name {dmi_rdata[27]}
set_db {port:raifes_dtm/dmi_rdata[26]} .original_name {dmi_rdata[26]}
set_db {port:raifes_dtm/dmi_rdata[25]} .original_name {dmi_rdata[25]}
set_db {port:raifes_dtm/dmi_rdata[24]} .original_name {dmi_rdata[24]}
set_db {port:raifes_dtm/dmi_rdata[23]} .original_name {dmi_rdata[23]}
set_db {port:raifes_dtm/dmi_rdata[22]} .original_name {dmi_rdata[22]}
set_db {port:raifes_dtm/dmi_rdata[21]} .original_name {dmi_rdata[21]}
set_db {port:raifes_dtm/dmi_rdata[20]} .original_name {dmi_rdata[20]}
set_db {port:raifes_dtm/dmi_rdata[19]} .original_name {dmi_rdata[19]}
set_db {port:raifes_dtm/dmi_rdata[18]} .original_name {dmi_rdata[18]}
set_db {port:raifes_dtm/dmi_rdata[17]} .original_name {dmi_rdata[17]}
set_db {port:raifes_dtm/dmi_rdata[16]} .original_name {dmi_rdata[16]}
set_db {port:raifes_dtm/dmi_rdata[15]} .original_name {dmi_rdata[15]}
set_db {port:raifes_dtm/dmi_rdata[14]} .original_name {dmi_rdata[14]}
set_db {port:raifes_dtm/dmi_rdata[13]} .original_name {dmi_rdata[13]}
set_db {port:raifes_dtm/dmi_rdata[12]} .original_name {dmi_rdata[12]}
set_db {port:raifes_dtm/dmi_rdata[11]} .original_name {dmi_rdata[11]}
set_db {port:raifes_dtm/dmi_rdata[10]} .original_name {dmi_rdata[10]}
set_db {port:raifes_dtm/dmi_rdata[9]} .original_name {dmi_rdata[9]}
set_db {port:raifes_dtm/dmi_rdata[8]} .original_name {dmi_rdata[8]}
set_db {port:raifes_dtm/dmi_rdata[7]} .original_name {dmi_rdata[7]}
set_db {port:raifes_dtm/dmi_rdata[6]} .original_name {dmi_rdata[6]}
set_db {port:raifes_dtm/dmi_rdata[5]} .original_name {dmi_rdata[5]}
set_db {port:raifes_dtm/dmi_rdata[4]} .original_name {dmi_rdata[4]}
set_db {port:raifes_dtm/dmi_rdata[3]} .original_name {dmi_rdata[3]}
set_db {port:raifes_dtm/dmi_rdata[2]} .original_name {dmi_rdata[2]}
set_db {port:raifes_dtm/dmi_rdata[1]} .original_name {dmi_rdata[1]}
set_db {port:raifes_dtm/dmi_rdata[0]} .original_name {dmi_rdata[0]}
set_db port:raifes_dtm/dmi_error .original_name {dmi_error}
set_db port:raifes_dtm/dmi_dm_busy .original_name {dmi_dm_busy}
set_db {port:raifes_dtm/adc_data[15]} .original_name {adc_data[15]}
set_db {port:raifes_dtm/adc_data[14]} .original_name {adc_data[14]}
set_db {port:raifes_dtm/adc_data[13]} .original_name {adc_data[13]}
set_db {port:raifes_dtm/adc_data[12]} .original_name {adc_data[12]}
set_db {port:raifes_dtm/adc_data[11]} .original_name {adc_data[11]}
set_db {port:raifes_dtm/adc_data[10]} .original_name {adc_data[10]}
set_db {port:raifes_dtm/adc_data[9]} .original_name {adc_data[9]}
set_db {port:raifes_dtm/adc_data[8]} .original_name {adc_data[8]}
set_db {port:raifes_dtm/adc_data[7]} .original_name {adc_data[7]}
set_db {port:raifes_dtm/adc_data[6]} .original_name {adc_data[6]}
set_db {port:raifes_dtm/adc_data[5]} .original_name {adc_data[5]}
set_db {port:raifes_dtm/adc_data[4]} .original_name {adc_data[4]}
set_db {port:raifes_dtm/adc_data[3]} .original_name {adc_data[3]}
set_db {port:raifes_dtm/adc_data[2]} .original_name {adc_data[2]}
set_db {port:raifes_dtm/adc_data[1]} .original_name {adc_data[1]}
set_db {port:raifes_dtm/adc_data[0]} .original_name {adc_data[0]}
set_db port:raifes_dtm/tdo .original_name {tdo}
set_db {port:raifes_dtm/dmi_addr[6]} .original_name {dmi_addr[6]}
set_db {port:raifes_dtm/dmi_addr[5]} .original_name {dmi_addr[5]}
set_db {port:raifes_dtm/dmi_addr[4]} .original_name {dmi_addr[4]}
set_db {port:raifes_dtm/dmi_addr[3]} .original_name {dmi_addr[3]}
set_db {port:raifes_dtm/dmi_addr[2]} .original_name {dmi_addr[2]}
set_db {port:raifes_dtm/dmi_addr[1]} .original_name {dmi_addr[1]}
set_db {port:raifes_dtm/dmi_addr[0]} .original_name {dmi_addr[0]}
set_db {port:raifes_dtm/dmi_wdata[31]} .original_name {dmi_wdata[31]}
set_db {port:raifes_dtm/dmi_wdata[30]} .original_name {dmi_wdata[30]}
set_db {port:raifes_dtm/dmi_wdata[29]} .original_name {dmi_wdata[29]}
set_db {port:raifes_dtm/dmi_wdata[28]} .original_name {dmi_wdata[28]}
set_db {port:raifes_dtm/dmi_wdata[27]} .original_name {dmi_wdata[27]}
set_db {port:raifes_dtm/dmi_wdata[26]} .original_name {dmi_wdata[26]}
set_db {port:raifes_dtm/dmi_wdata[25]} .original_name {dmi_wdata[25]}
set_db {port:raifes_dtm/dmi_wdata[24]} .original_name {dmi_wdata[24]}
set_db {port:raifes_dtm/dmi_wdata[23]} .original_name {dmi_wdata[23]}
set_db {port:raifes_dtm/dmi_wdata[22]} .original_name {dmi_wdata[22]}
set_db {port:raifes_dtm/dmi_wdata[21]} .original_name {dmi_wdata[21]}
set_db {port:raifes_dtm/dmi_wdata[20]} .original_name {dmi_wdata[20]}
set_db {port:raifes_dtm/dmi_wdata[19]} .original_name {dmi_wdata[19]}
set_db {port:raifes_dtm/dmi_wdata[18]} .original_name {dmi_wdata[18]}
set_db {port:raifes_dtm/dmi_wdata[17]} .original_name {dmi_wdata[17]}
set_db {port:raifes_dtm/dmi_wdata[16]} .original_name {dmi_wdata[16]}
set_db {port:raifes_dtm/dmi_wdata[15]} .original_name {dmi_wdata[15]}
set_db {port:raifes_dtm/dmi_wdata[14]} .original_name {dmi_wdata[14]}
set_db {port:raifes_dtm/dmi_wdata[13]} .original_name {dmi_wdata[13]}
set_db {port:raifes_dtm/dmi_wdata[12]} .original_name {dmi_wdata[12]}
set_db {port:raifes_dtm/dmi_wdata[11]} .original_name {dmi_wdata[11]}
set_db {port:raifes_dtm/dmi_wdata[10]} .original_name {dmi_wdata[10]}
set_db {port:raifes_dtm/dmi_wdata[9]} .original_name {dmi_wdata[9]}
set_db {port:raifes_dtm/dmi_wdata[8]} .original_name {dmi_wdata[8]}
set_db {port:raifes_dtm/dmi_wdata[7]} .original_name {dmi_wdata[7]}
set_db {port:raifes_dtm/dmi_wdata[6]} .original_name {dmi_wdata[6]}
set_db {port:raifes_dtm/dmi_wdata[5]} .original_name {dmi_wdata[5]}
set_db {port:raifes_dtm/dmi_wdata[4]} .original_name {dmi_wdata[4]}
set_db {port:raifes_dtm/dmi_wdata[3]} .original_name {dmi_wdata[3]}
set_db {port:raifes_dtm/dmi_wdata[2]} .original_name {dmi_wdata[2]}
set_db {port:raifes_dtm/dmi_wdata[1]} .original_name {dmi_wdata[1]}
set_db {port:raifes_dtm/dmi_wdata[0]} .original_name {dmi_wdata[0]}
set_db port:raifes_dtm/dmi_en .original_name {dmi_en}
set_db port:raifes_dtm/dmi_wen .original_name {dmi_wen}
set_db {port:raifes_dtm/adc_ctrl[15]} .original_name {adc_ctrl[15]}
set_db {port:raifes_dtm/adc_ctrl[14]} .original_name {adc_ctrl[14]}
set_db {port:raifes_dtm/adc_ctrl[13]} .original_name {adc_ctrl[13]}
set_db {port:raifes_dtm/adc_ctrl[12]} .original_name {adc_ctrl[12]}
set_db {port:raifes_dtm/adc_ctrl[11]} .original_name {adc_ctrl[11]}
set_db {port:raifes_dtm/adc_ctrl[10]} .original_name {adc_ctrl[10]}
set_db {port:raifes_dtm/adc_ctrl[9]} .original_name {adc_ctrl[9]}
set_db {port:raifes_dtm/adc_ctrl[8]} .original_name {adc_ctrl[8]}
set_db {port:raifes_dtm/adc_ctrl[7]} .original_name {adc_ctrl[7]}
set_db {port:raifes_dtm/adc_ctrl[6]} .original_name {adc_ctrl[6]}
set_db {port:raifes_dtm/adc_ctrl[5]} .original_name {adc_ctrl[5]}
set_db {port:raifes_dtm/adc_ctrl[4]} .original_name {adc_ctrl[4]}
set_db {port:raifes_dtm/adc_ctrl[3]} .original_name {adc_ctrl[3]}
set_db {port:raifes_dtm/adc_ctrl[2]} .original_name {adc_ctrl[2]}
set_db {port:raifes_dtm/adc_ctrl[1]} .original_name {adc_ctrl[1]}
set_db {port:raifes_dtm/adc_ctrl[0]} .original_name {adc_ctrl[0]}
set_db {port:raifes_dtm/puf_ctrl[31]} .original_name {puf_ctrl[31]}
set_db {port:raifes_dtm/puf_ctrl[30]} .original_name {puf_ctrl[30]}
set_db {port:raifes_dtm/puf_ctrl[29]} .original_name {puf_ctrl[29]}
set_db {port:raifes_dtm/puf_ctrl[28]} .original_name {puf_ctrl[28]}
set_db {port:raifes_dtm/puf_ctrl[27]} .original_name {puf_ctrl[27]}
set_db {port:raifes_dtm/puf_ctrl[26]} .original_name {puf_ctrl[26]}
set_db {port:raifes_dtm/puf_ctrl[25]} .original_name {puf_ctrl[25]}
set_db {port:raifes_dtm/puf_ctrl[24]} .original_name {puf_ctrl[24]}
set_db {port:raifes_dtm/puf_ctrl[23]} .original_name {puf_ctrl[23]}
set_db {port:raifes_dtm/puf_ctrl[22]} .original_name {puf_ctrl[22]}
set_db {port:raifes_dtm/puf_ctrl[21]} .original_name {puf_ctrl[21]}
set_db {port:raifes_dtm/puf_ctrl[20]} .original_name {puf_ctrl[20]}
set_db {port:raifes_dtm/puf_ctrl[19]} .original_name {puf_ctrl[19]}
set_db {port:raifes_dtm/puf_ctrl[18]} .original_name {puf_ctrl[18]}
set_db {port:raifes_dtm/puf_ctrl[17]} .original_name {puf_ctrl[17]}
set_db {port:raifes_dtm/puf_ctrl[16]} .original_name {puf_ctrl[16]}
set_db {port:raifes_dtm/puf_ctrl[15]} .original_name {puf_ctrl[15]}
set_db {port:raifes_dtm/puf_ctrl[14]} .original_name {puf_ctrl[14]}
set_db {port:raifes_dtm/puf_ctrl[13]} .original_name {puf_ctrl[13]}
set_db {port:raifes_dtm/puf_ctrl[12]} .original_name {puf_ctrl[12]}
set_db {port:raifes_dtm/puf_ctrl[11]} .original_name {puf_ctrl[11]}
set_db {port:raifes_dtm/puf_ctrl[10]} .original_name {puf_ctrl[10]}
set_db {port:raifes_dtm/puf_ctrl[9]} .original_name {puf_ctrl[9]}
set_db {port:raifes_dtm/puf_ctrl[8]} .original_name {puf_ctrl[8]}
set_db {port:raifes_dtm/puf_ctrl[7]} .original_name {puf_ctrl[7]}
set_db {port:raifes_dtm/puf_ctrl[6]} .original_name {puf_ctrl[6]}
set_db {port:raifes_dtm/puf_ctrl[5]} .original_name {puf_ctrl[5]}
set_db {port:raifes_dtm/puf_ctrl[4]} .original_name {puf_ctrl[4]}
set_db {port:raifes_dtm/puf_ctrl[3]} .original_name {puf_ctrl[3]}
set_db {port:raifes_dtm/puf_ctrl[2]} .original_name {puf_ctrl[2]}
set_db {port:raifes_dtm/puf_ctrl[1]} .original_name {puf_ctrl[1]}
set_db {port:raifes_dtm/puf_ctrl[0]} .original_name {puf_ctrl[0]}
set_db {port:raifes_dtm/debug_state[3]} .original_name {debug_state[3]}
set_db {port:raifes_dtm/debug_state[2]} .original_name {debug_state[2]}
set_db {port:raifes_dtm/debug_state[1]} .original_name {debug_state[1]}
set_db {port:raifes_dtm/debug_state[0]} .original_name {debug_state[0]}



set_db {pin:raifes_dtm/DMI_reg[1]/Q} .original_name {DMI[1]/q}
set_db {pin:raifes_dtm/DMI_reg[28]/Q} .original_name {DMI[28]/q}
set_db {pin:raifes_dtm/DMI_reg[19]/Q} .original_name {DMI[19]/q}
set_db {pin:raifes_dtm/DMI_reg[21]/Q} .original_name {DMI[21]/q}
set_db {pin:raifes_dtm/DMI_reg[22]/Q} .original_name {DMI[22]/q}
set_db {pin:raifes_dtm/DMI_reg[23]/Q} .original_name {DMI[23]/q}
set_db {pin:raifes_dtm/DMI_reg[24]/Q} .original_name {DMI[24]/q}
set_db {pin:raifes_dtm/DMI_reg[25]/Q} .original_name {DMI[25]/q}
set_db {pin:raifes_dtm/DMI_reg[26]/Q} .original_name {DMI[26]/q}
set_db {pin:raifes_dtm/DMI_reg[27]/Q} .original_name {DMI[27]/q}
set_db {pin:raifes_dtm/DMI_reg[40]/Q} .original_name {DMI[40]/q}
set_db {pin:raifes_dtm/DMI_reg[29]/Q} .original_name {DMI[29]/q}
set_db {pin:raifes_dtm/DMI_reg[30]/Q} .original_name {DMI[30]/q}
set_db {pin:raifes_dtm/DMI_reg[31]/Q} .original_name {DMI[31]/q}
set_db {pin:raifes_dtm/DMI_reg[32]/Q} .original_name {DMI[32]/q}
set_db {pin:raifes_dtm/DMI_reg[33]/Q} .original_name {DMI[33]/q}
set_db {pin:raifes_dtm/DMI_reg[2]/Q} .original_name {DMI[2]/q}
set_db {pin:raifes_dtm/DMI_reg[3]/Q} .original_name {DMI[3]/q}
set_db {pin:raifes_dtm/DMI_reg[34]/Q} .original_name {DMI[34]/q}
set_db {pin:raifes_dtm/DMI_reg[39]/Q} .original_name {DMI[39]/q}
set_db {pin:raifes_dtm/DMI_reg[0]/Q} .original_name {DMI[0]/q}
set_db {pin:raifes_dtm/DMI_reg[36]/Q} .original_name {DMI[36]/q}
set_db {pin:raifes_dtm/DMI_reg[37]/Q} .original_name {DMI[37]/q}
set_db {pin:raifes_dtm/DMI_reg[20]/Q} .original_name {DMI[20]/q}
set_db {pin:raifes_dtm/DMI_reg[38]/Q} .original_name {DMI[38]/q}
set_db {pin:raifes_dtm/DMI_reg[4]/Q} .original_name {DMI[4]/q}
set_db {pin:raifes_dtm/DMI_reg[18]/Q} .original_name {DMI[18]/q}
set_db {pin:raifes_dtm/DMI_reg[17]/Q} .original_name {DMI[17]/q}
set_db {pin:raifes_dtm/DMI_reg[16]/Q} .original_name {DMI[16]/q}
set_db {pin:raifes_dtm/DMI_reg[15]/Q} .original_name {DMI[15]/q}
set_db {pin:raifes_dtm/DMI_reg[14]/Q} .original_name {DMI[14]/q}
set_db {pin:raifes_dtm/DMI_reg[13]/Q} .original_name {DMI[13]/q}
set_db {pin:raifes_dtm/DMI_reg[12]/Q} .original_name {DMI[12]/q}
set_db {pin:raifes_dtm/DMI_reg[11]/Q} .original_name {DMI[11]/q}
set_db {pin:raifes_dtm/DMI_reg[10]/Q} .original_name {DMI[10]/q}
set_db {pin:raifes_dtm/DMI_reg[9]/Q} .original_name {DMI[9]/q}
set_db {pin:raifes_dtm/DMI_reg[8]/Q} .original_name {DMI[8]/q}
set_db {pin:raifes_dtm/DMI_reg[7]/Q} .original_name {DMI[7]/q}
set_db {pin:raifes_dtm/DMI_reg[6]/Q} .original_name {DMI[6]/q}
set_db {pin:raifes_dtm/DMI_reg[5]/Q} .original_name {DMI[5]/q}
set_db {pin:raifes_dtm/DMI_reg[35]/Q} .original_name {DMI[35]/q}
set_db pin:raifes_dtm/tdo_r_reg/Q .original_name {tdo_r/q}
set_db {pin:raifes_dtm/DTM_reg[5]/Q} .original_name {DTM[5]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[2]/Q} .original_name {ADCDATA[2]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[3]/Q} .original_name {ADCDATA[3]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[4]/Q} .original_name {ADCDATA[4]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[5]/Q} .original_name {ADCDATA[5]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[6]/Q} .original_name {ADCDATA[6]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[1]/Q} .original_name {ADCDATA[1]/q}
set_db {pin:raifes_dtm/state_reg[0]/Q} .original_name {state[0]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[9]/Q} .original_name {ADCDATA[9]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[10]/Q} .original_name {ADCDATA[10]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[11]/Q} .original_name {ADCDATA[11]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[12]/Q} .original_name {ADCDATA[12]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[13]/Q} .original_name {ADCDATA[13]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[14]/Q} .original_name {ADCDATA[14]/q}
set_db {pin:raifes_dtm/DTM_reg[22]/Q} .original_name {DTM[22]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[15]/Q} .original_name {ADCDATA[15]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[0]/Q} .original_name {ADCDATA[0]/q}
set_db {pin:raifes_dtm/DTM_reg[2]/Q} .original_name {DTM[2]/q}
set_db {pin:raifes_dtm/DTM_reg[3]/Q} .original_name {DTM[3]/q}
set_db {pin:raifes_dtm/DTM_reg[7]/Q} .original_name {DTM[7]/q}
set_db {pin:raifes_dtm/DTM_reg[8]/Q} .original_name {DTM[8]/q}
set_db {pin:raifes_dtm/DTM_reg[9]/Q} .original_name {DTM[9]/q}
set_db {pin:raifes_dtm/DTM_reg[10]/Q} .original_name {DTM[10]/q}
set_db {pin:raifes_dtm/DTM_reg[11]/Q} .original_name {DTM[11]/q}
set_db {pin:raifes_dtm/DTM_reg[12]/Q} .original_name {DTM[12]/q}
set_db {pin:raifes_dtm/DTM_reg[14]/Q} .original_name {DTM[14]/q}
set_db {pin:raifes_dtm/DTM_reg[15]/Q} .original_name {DTM[15]/q}
set_db {pin:raifes_dtm/DTM_reg[18]/Q} .original_name {DTM[18]/q}
set_db {pin:raifes_dtm/DTM_reg[24]/Q} .original_name {DTM[24]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[7]/Q} .original_name {ADCDATA[7]/q}
set_db {pin:raifes_dtm/DTM_reg[20]/Q} .original_name {DTM[20]/q}
set_db {pin:raifes_dtm/DTM_reg[21]/Q} .original_name {DTM[21]/q}
set_db {pin:raifes_dtm/DTM_reg[16]/Q} .original_name {DTM[16]/q}
set_db {pin:raifes_dtm/DTM_reg[17]/Q} .original_name {DTM[17]/q}
set_db {pin:raifes_dtm/DTM_reg[23]/Q} .original_name {DTM[23]/q}
set_db {pin:raifes_dtm/DTM_reg[1]/Q} .original_name {DTM[1]/q}
set_db {pin:raifes_dtm/DTM_reg[19]/Q} .original_name {DTM[19]/q}
set_db {pin:raifes_dtm/DTM_reg[30]/Q} .original_name {DTM[30]/q}
set_db {pin:raifes_dtm/DTM_reg[26]/Q} .original_name {DTM[26]/q}
set_db {pin:raifes_dtm/DTM_reg[27]/Q} .original_name {DTM[27]/q}
set_db {pin:raifes_dtm/DTM_reg[0]/Q} .original_name {DTM[0]/q}
set_db {pin:raifes_dtm/DTM_reg[4]/Q} .original_name {DTM[4]/q}
set_db {pin:raifes_dtm/DTM_reg[6]/Q} .original_name {DTM[6]/q}
set_db {pin:raifes_dtm/DTM_reg[13]/Q} .original_name {DTM[13]/q}
set_db {pin:raifes_dtm/DTM_reg[28]/Q} .original_name {DTM[28]/q}
set_db {pin:raifes_dtm/DTM_reg[25]/Q} .original_name {DTM[25]/q}
set_db {pin:raifes_dtm/DTM_reg[29]/Q} .original_name {DTM[29]/q}
set_db {pin:raifes_dtm/ADCDATA_reg[8]/Q} .original_name {ADCDATA[8]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[13]/Q} .original_name {ADCCTRL[13]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[6]/Q} .original_name {ADCCTRL[6]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[8]/Q} .original_name {ADCCTRL[8]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[4]/Q} .original_name {ADCCTRL[4]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[1]/Q} .original_name {ADCCTRL[1]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[0]/Q} .original_name {ADCCTRL[0]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[11]/Q} .original_name {ADCCTRL[11]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[9]/Q} .original_name {ADCCTRL[9]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[7]/Q} .original_name {ADCCTRL[7]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[5]/Q} .original_name {ADCCTRL[5]/q}
set_db {pin:raifes_dtm/DTM_reg[31]/Q} .original_name {DTM[31]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[3]/Q} .original_name {ADCCTRL[3]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[12]/Q} .original_name {ADCCTRL[12]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[10]/Q} .original_name {ADCCTRL[10]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[14]/Q} .original_name {ADCCTRL[14]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[2]/Q} .original_name {ADCCTRL[2]/q}
set_db {pin:raifes_dtm/IDCODE_reg[1]/Q} .original_name {IDCODE[1]/q}
set_db {pin:raifes_dtm/IDCODE_reg[2]/Q} .original_name {IDCODE[2]/q}
set_db {pin:raifes_dtm/IDCODE_reg[3]/Q} .original_name {IDCODE[3]/q}
set_db {pin:raifes_dtm/IDCODE_reg[21]/Q} .original_name {IDCODE[21]/q}
set_db {pin:raifes_dtm/IDCODE_reg[22]/Q} .original_name {IDCODE[22]/q}
set_db {pin:raifes_dtm/IDCODE_reg[23]/Q} .original_name {IDCODE[23]/q}
set_db {pin:raifes_dtm/IDCODE_reg[24]/Q} .original_name {IDCODE[24]/q}
set_db {pin:raifes_dtm/IDCODE_reg[25]/Q} .original_name {IDCODE[25]/q}
set_db {pin:raifes_dtm/IDCODE_reg[26]/Q} .original_name {IDCODE[26]/q}
set_db {pin:raifes_dtm/IDCODE_reg[27]/Q} .original_name {IDCODE[27]/q}
set_db {pin:raifes_dtm/IDCODE_reg[30]/Q} .original_name {IDCODE[30]/q}
set_db {pin:raifes_dtm/IDCODE_reg[0]/Q} .original_name {IDCODE[0]/q}
set_db {pin:raifes_dtm/IDCODE_reg[12]/Q} .original_name {IDCODE[12]/q}
set_db {pin:raifes_dtm/IDCODE_reg[4]/Q} .original_name {IDCODE[4]/q}
set_db {pin:raifes_dtm/state_reg[1]/Q} .original_name {state[1]/q}
set_db {pin:raifes_dtm/IDCODE_reg[5]/Q} .original_name {IDCODE[5]/q}
set_db {pin:raifes_dtm/state_reg[3]/Q} .original_name {state[3]/q}
set_db {pin:raifes_dtm/IDCODE_reg[6]/Q} .original_name {IDCODE[6]/q}
set_db {pin:raifes_dtm/IDCODE_reg[28]/Q} .original_name {IDCODE[28]/q}
set_db {pin:raifes_dtm/IDCODE_reg[7]/Q} .original_name {IDCODE[7]/q}
set_db {pin:raifes_dtm/IDCODE_reg[8]/Q} .original_name {IDCODE[8]/q}
set_db {pin:raifes_dtm/IDCODE_reg[9]/Q} .original_name {IDCODE[9]/q}
set_db {pin:raifes_dtm/IDCODE_reg[20]/Q} .original_name {IDCODE[20]/q}
set_db {pin:raifes_dtm/IDCODE_reg[10]/Q} .original_name {IDCODE[10]/q}
set_db {pin:raifes_dtm/IDCODE_reg[13]/Q} .original_name {IDCODE[13]/q}
set_db {pin:raifes_dtm/IDCODE_reg[14]/Q} .original_name {IDCODE[14]/q}
set_db {pin:raifes_dtm/IDCODE_reg[15]/Q} .original_name {IDCODE[15]/q}
set_db {pin:raifes_dtm/IDCODE_reg[17]/Q} .original_name {IDCODE[17]/q}
set_db {pin:raifes_dtm/IDCODE_reg[29]/Q} .original_name {IDCODE[29]/q}
set_db {pin:raifes_dtm/IDCODE_reg[16]/Q} .original_name {IDCODE[16]/q}
set_db {pin:raifes_dtm/IDCODE_reg[11]/Q} .original_name {IDCODE[11]/q}
set_db {pin:raifes_dtm/IDCODE_reg[18]/Q} .original_name {IDCODE[18]/q}
set_db {pin:raifes_dtm/IDCODE_reg[19]/Q} .original_name {IDCODE[19]/q}
set_db {pin:raifes_dtm/IR_shift_reg[0]/Q} .original_name {IR_shift[0]/q}
set_db {pin:raifes_dtm/ADCCTRL_reg[15]/Q} .original_name {ADCCTRL[15]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[20]/Q} .original_name {PUFCTRL[20]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[0]/Q} .original_name {PUFCTRL[0]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[1]/Q} .original_name {PUFCTRL[1]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[8]/Q} .original_name {PUFCTRL[8]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[2]/Q} .original_name {PUFCTRL[2]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[22]/Q} .original_name {PUFCTRL[22]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[14]/Q} .original_name {PUFCTRL[14]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[17]/Q} .original_name {PUFCTRL[17]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[4]/Q} .original_name {PUFCTRL[4]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[24]/Q} .original_name {PUFCTRL[24]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[29]/Q} .original_name {PUFCTRL[29]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[9]/Q} .original_name {PUFCTRL[9]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[10]/Q} .original_name {PUFCTRL[10]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[11]/Q} .original_name {PUFCTRL[11]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[13]/Q} .original_name {PUFCTRL[13]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[15]/Q} .original_name {PUFCTRL[15]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[16]/Q} .original_name {PUFCTRL[16]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[3]/Q} .original_name {PUFCTRL[3]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[19]/Q} .original_name {PUFCTRL[19]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[21]/Q} .original_name {PUFCTRL[21]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[25]/Q} .original_name {PUFCTRL[25]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[30]/Q} .original_name {PUFCTRL[30]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[27]/Q} .original_name {PUFCTRL[27]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[23]/Q} .original_name {PUFCTRL[23]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[12]/Q} .original_name {PUFCTRL[12]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[18]/Q} .original_name {PUFCTRL[18]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[5]/Q} .original_name {PUFCTRL[5]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[26]/Q} .original_name {PUFCTRL[26]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[28]/Q} .original_name {PUFCTRL[28]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[7]/Q} .original_name {PUFCTRL[7]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[6]/Q} .original_name {PUFCTRL[6]/q}
set_db {pin:raifes_dtm/dmi_addr_reg[2]/Q} .original_name {dmi_addr[2]/q}
set_db pin:raifes_dtm/dmi_wen_reg/Q .original_name {dmi_wen/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[2]/Q} .original_name {dmi_wdata[2]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[10]/Q} .original_name {dmi_wdata[10]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[6]/Q} .original_name {dmi_wdata[6]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[21]/Q} .original_name {dmi_wdata[21]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[20]/Q} .original_name {dmi_wdata[20]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[19]/Q} .original_name {dmi_wdata[19]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[17]/Q} .original_name {dmi_wdata[17]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[16]/Q} .original_name {dmi_wdata[16]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[15]/Q} .original_name {dmi_wdata[15]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[28]/Q} .original_name {dmi_wdata[28]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[13]/Q} .original_name {dmi_wdata[13]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[12]/Q} .original_name {dmi_wdata[12]/q}
set_db {pin:raifes_dtm/dmi_addr_reg[1]/Q} .original_name {dmi_addr[1]/q}
set_db pin:raifes_dtm/dmi_en_reg/Q .original_name {dmi_en/q}
set_db {pin:raifes_dtm/dmi_addr_reg[0]/Q} .original_name {dmi_addr[0]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[14]/Q} .original_name {dmi_wdata[14]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[31]/Q} .original_name {dmi_wdata[31]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[30]/Q} .original_name {dmi_wdata[30]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[29]/Q} .original_name {dmi_wdata[29]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[0]/Q} .original_name {dmi_wdata[0]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[1]/Q} .original_name {dmi_wdata[1]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[3]/Q} .original_name {dmi_wdata[3]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[4]/Q} .original_name {dmi_wdata[4]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[5]/Q} .original_name {dmi_wdata[5]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[7]/Q} .original_name {dmi_wdata[7]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[8]/Q} .original_name {dmi_wdata[8]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[9]/Q} .original_name {dmi_wdata[9]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[24]/Q} .original_name {dmi_wdata[24]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[25]/Q} .original_name {dmi_wdata[25]/q}
set_db {pin:raifes_dtm/dmi_addr_reg[6]/Q} .original_name {dmi_addr[6]/q}
set_db {pin:raifes_dtm/dmi_addr_reg[3]/Q} .original_name {dmi_addr[3]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[11]/Q} .original_name {dmi_wdata[11]/q}
set_db {pin:raifes_dtm/dmi_addr_reg[4]/Q} .original_name {dmi_addr[4]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[27]/Q} .original_name {dmi_wdata[27]/q}
set_db {pin:raifes_dtm/dmi_addr_reg[5]/Q} .original_name {dmi_addr[5]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[26]/Q} .original_name {dmi_wdata[26]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[22]/Q} .original_name {dmi_wdata[22]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[18]/Q} .original_name {dmi_wdata[18]/q}
set_db {pin:raifes_dtm/dmi_wdata_reg[23]/Q} .original_name {dmi_wdata[23]/q}
set_db {pin:raifes_dtm/state_reg[2]/Q} .original_name {state[2]/q}
set_db {pin:raifes_dtm/PUFCTRL_reg[31]/Q} .original_name {PUFCTRL[31]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[13]/Q} .original_name {adc_ctrl[13]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[14]/Q} .original_name {adc_ctrl[14]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[9]/Q} .original_name {adc_ctrl[9]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[1]/Q} .original_name {adc_ctrl[1]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[10]/Q} .original_name {adc_ctrl[10]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[15]/Q} .original_name {adc_ctrl[15]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[2]/Q} .original_name {adc_ctrl[2]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[12]/Q} .original_name {adc_ctrl[12]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[11]/Q} .original_name {adc_ctrl[11]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[8]/Q} .original_name {adc_ctrl[8]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[7]/Q} .original_name {adc_ctrl[7]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[6]/Q} .original_name {adc_ctrl[6]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[5]/Q} .original_name {adc_ctrl[5]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[4]/Q} .original_name {adc_ctrl[4]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[3]/Q} .original_name {adc_ctrl[3]/q}
set_db {pin:raifes_dtm/adc_ctrl_reg[0]/Q} .original_name {adc_ctrl[0]/q}
set_db {pin:raifes_dtm/IDCODE_reg[31]/Q} .original_name {IDCODE[31]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[26]/Q} .original_name {puf_ctrl[26]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[19]/Q} .original_name {puf_ctrl[19]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[9]/Q} .original_name {puf_ctrl[9]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[15]/Q} .original_name {puf_ctrl[15]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[16]/Q} .original_name {puf_ctrl[16]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[20]/Q} .original_name {puf_ctrl[20]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[10]/Q} .original_name {puf_ctrl[10]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[12]/Q} .original_name {puf_ctrl[12]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[30]/Q} .original_name {puf_ctrl[30]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[27]/Q} .original_name {puf_ctrl[27]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[18]/Q} .original_name {puf_ctrl[18]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[31]/Q} .original_name {puf_ctrl[31]/q}
set_db {pin:raifes_dtm/IR_shift_reg[1]/Q} .original_name {IR_shift[1]/q}
set_db {pin:raifes_dtm/IR_shift_reg[3]/Q} .original_name {IR_shift[3]/q}
set_db {pin:raifes_dtm/IR_reg[2]/Q} .original_name {IR[2]/q}
set_db {pin:raifes_dtm/IR_shift_reg[2]/Q} .original_name {IR_shift[2]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[8]/Q} .original_name {puf_ctrl[8]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[25]/Q} .original_name {puf_ctrl[25]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[21]/Q} .original_name {puf_ctrl[21]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[17]/Q} .original_name {puf_ctrl[17]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[14]/Q} .original_name {puf_ctrl[14]/q}
set_db {pin:raifes_dtm/IR_reg[1]/Q} .original_name {IR[1]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[22]/Q} .original_name {puf_ctrl[22]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[29]/Q} .original_name {puf_ctrl[29]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[23]/Q} .original_name {puf_ctrl[23]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[0]/Q} .original_name {puf_ctrl[0]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[6]/Q} .original_name {puf_ctrl[6]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[24]/Q} .original_name {puf_ctrl[24]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[1]/Q} .original_name {puf_ctrl[1]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[2]/Q} .original_name {puf_ctrl[2]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[11]/Q} .original_name {puf_ctrl[11]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[7]/Q} .original_name {puf_ctrl[7]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[5]/Q} .original_name {puf_ctrl[5]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[4]/Q} .original_name {puf_ctrl[4]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[3]/Q} .original_name {puf_ctrl[3]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[13]/Q} .original_name {puf_ctrl[13]/q}
set_db {pin:raifes_dtm/puf_ctrl_reg[28]/Q} .original_name {puf_ctrl[28]/q}
set_db {pin:raifes_dtm/IR_shift_reg[4]/Q} .original_name {IR_shift[4]/q}
set_db {pin:raifes_dtm/IR_reg[3]/Q} .original_name {IR[3]/q}
set_db {pin:raifes_dtm/IR_reg[4]/Q} .original_name {IR[4]/q}
set_db {pin:raifes_dtm/IR_reg[0]/Q} .original_name {IR[0]/q}
